services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/prowlarr:/config
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/radarr:/config
      - ${MOVIES_LIBRARY_PATH}:/movies
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/sonarr:/config
      - ${SHOWS_LIBRARY_PATH}:/shows
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/lidarr:/config
      - ${MUSIC_LIBRARY_PATH}:/music
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG_BASE_PATH}/qbittorrent:/config
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/jellyfin:/config
      - ${SHOWS_LIBRARY_PATH}:/shows
      - ${MOVIES_LIBRARY_PATH}:/movies
      - ${MUSIC_LIBRARY_PATH}:/music
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    devices:
      - /dev/dri:/dev/dri

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/jellyseerr:/app/config
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ${CONFIG_BASE_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOMEPAGE_ALLOWED_HOSTS:gethomepage.dev
      - PUID=${PUID}
      - PGID=${PGID}

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
    ports:
      - 8989:8989     # sonarr
      - 7878:7878     # radarr
      - 8686:8686     # lidarr
      - 9696:9696     # prowlarr
      - 8080:8080     # qbittorrent
      - 6881:6881     # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 8191:8191     # flaresolverr
      - 8096:8096     # jellyfin
      - 5055:5055     # jellyseerr
