networks:
  media_net:
  vpn_net:

include:
  - stack/nginx.yml
  - stack/prowlarr.yml
  - stack/radarr.yml
  - stack/sonarr.yml
  - stack/nicotine.yml
  - stack/qbittorrent.yml
  - stack/flaresolverr.yml
  - stack/jellyfin.yml
  - stack/seerr.yml
  - stack/notifiarr.yml
  - stack/homepage.yml
  - stack/gluetun.yml
  - stack/dnsmasq.yml
  - stack/navidrome.yml
  - stack/bazarr.yml
