include:
  - stack/prowlarr.yml
  - stack/radarr.yml
  - stack/sonarr.yml
  - stack/lidarr.yml
  - stack/qbittorrent.yml
  - stack/flaresolverr.yml
  - stack/jellyfin.yml
  - stack/jellyseerr.yml
  - stack/notifiarr.yml
  - stack/homepage.yml
  - stack/gluetun.yml
  - stack/dnsmasq.yml
