apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinepods-postgres
  namespace: media
  labels:
    app: pinepods-postgres
    app.kubernetes.io/name: pinepods-postgres
    app.kubernetes.io/instance: pinepods-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinepods-postgres
  template:
    metadata:
      labels:
        app: pinepods-postgres
        app.kubernetes.io/name: pinepods-postgres
        app.kubernetes.io/instance: pinepods-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_DB
              value: pinepods_database
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pinepods-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pinepods-postgres
