apiVersion: ENC[AES256_GCM,data:q9w=,iv:i4vFcz4DGtPxs2UFgjDtKB3UXnEtkX8Ej0iHBkczhFc=,tag:qFG/Vh6XNzQMjUhLaLiUyw==,type:str]
kind: ENC[AES256_GCM,data:3PiBVFrR,iv:4PJMYkKVq67R4NjezSs0un0fUeCEeKC/xeBak/Y2Gdk=,tag:MVt9mJKWtJG1UdyOmji0WQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MQsk4qhfx7CpabmGpyBm,iv:VwCd9eVH1u8x3gNjE+hIFqdcaJknQ3zQ44c+aT4c/0E=,tag:JGzN/H05Zn/tGGy9C3I8SQ==,type:str]
    namespace: ENC[AES256_GCM,data:iO574ps=,iv:HcsSQKk0k2WVC4/F476lK6J+IU7gRr1N+wXjGuWI20I=,tag:zCrOAiZ6/t5ESYvPSLUbAQ==,type:str]
type: ENC[AES256_GCM,data:kIz1gFaF,iv:m5Z4zgE+tCHE5mm777JGChq2huvrphQQBNpt94XQMt0=,tag:mzFnk0L2z/P1qFUf97q2mQ==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VASCIMDHrBmMmYlLVaX1bjgeLuAtWgpqgic1TcKW/T7lq6wtqnn4FZXqi1M=,iv:HipCx5Miv4aZq2nVy2IXYfXFTt/0Mga7BKS2G3qCGWM=,tag:CZ8Mm+FdrSUTpimN3bEpQg==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:knJ4SQ==,iv:V6G66It2/VPp51nlAmDhFWDDorUraINOJZ8X77yD1fY=,tag:VVxxbjHneszVuP6W6C2sCw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:2nqJQ2DnsyLgg5TlygRIw/3vbkYIVqTz47HAHRexLOuHqvjly5OzPR5jk2g=,iv:M6LGmb6y9ZDICJU1o/86x4RpvG1Ds7RkxTIvvH1x57E=,tag:kYcJGVKZz7E8OkSS7MD3IA==,type:str]
    ADMIN_FULLNAME: ENC[AES256_GCM,data:cn6Jmw==,iv:AJ3iKgTw3hVFvSoKM+R1cv4L4lS/0SDHG0CWuwrsXdA=,tag:+UxXEi5YftKd2NM0hKDd1Q==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:NiHlXtlySC66XQGazRhnWF7QJgQkZvHMWQ==,iv:3glUlkeNAPbC+jYRgezGSfKjAK2QSqPnYQhpqEONlUE=,tag:jSCx9JPTVFIkUa3kdChzuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZclNhY3RkNEM2T2N1cW5Y
            QktSeE9vV3V4bmhyWmIvODJydXZZKzZ6dmpZCk5SSWJPVVpwaEJHMjZadjhzWU5t
            N2pxaW4zRUdLd2FaOWZENGlYWndzUmMKLS0tIGhzd2xnNTFmNnF2U0ZzZ21oVnll
            d3pGTGxDWnlUZjgyNDVnRVFVbFpJSmsKJieXxDt86EN5qednlzn/H822+Auz2P7z
            uRz/521d47Q+BJ/49TF8VjFJ7312mwwfxDO6Domf/s8LVgFtzHdXzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-21T10:23:02Z"
    mac: ENC[AES256_GCM,data:sJE0ipNqh+3/M2/A4DkIOIe/cowvX+jN+eUZy9ldIZP5ayJPZ/FQHVQwUBRW560nZcTBu0EwERfLnAGe13RAkdiT5lELMyBXcC+shR9H0bRV6nPLCxG1zBqETK2aKwX1bA+uWZBzlwDMZm16x6CN3NViXHGVd3B1h3+2uIArt9c=,iv:5rSBwYbLZcDqylMMU7pHuuiaVlhiGG6Q5CB/IyOwk80=,tag:jkCFCq3eS0/r7KyBpO/z8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
