apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-config
  namespace: downloads
data:
  DNS_KEEP_NAMESERVER: "on"
  FIREWALL_OUTBOUND_SUBNETS: "10.42.0.0/15"
  VPN_SERVICE_PROVIDER: "protonvpn"
  VPN_TYPE: "wireguard"
  SERVER_COUNTRIES: "Netherlands"
  PORT_FORWARD_ONLY: "on"
  VPN_PORT_FORWARDING: "on"
