apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - freshrss
  - jellyfin
  - jelu
  - lidarr
  - droppedneedle
  - navidrome
  - pinepods
  - radarr
  - seerr
  - sonarr
  - soulsync
