apiVersion: ENC[AES256_GCM,data:qHg=,iv:835Jz9oEZ6VR1OZktoZIQZaPOvcjSariQ5YqJG6vTW0=,tag:eWScKe49RPS81Ew/VvxZ3A==,type:str]
kind: ENC[AES256_GCM,data:J76r6WcD,iv:6G3i000VCIwpwv9osI9mVBmHALnqCu6w6Yapru4Su7g=,tag:DtJV8UAuhHQQ8tVZoI1wAw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X9lIwoSUtIr7bz7mFU+hwG5NLg==,iv:Yd0ZtqHrwT0JuSdEGV3SBHBVURLjfwcIcC5FLGu59wc=,tag:q5h/QSth+GBN+OtQYCA7NQ==,type:str]
    namespace: ENC[AES256_GCM,data:qhNyDr7lwvCChaQ=,iv:f8AGoN0EuJXUIkQB2xoxOUTc5N1uqMOhXABrPnQibBQ=,tag:HuBqPVGXwMsRYo4wPur+3Q==,type:str]
type: ENC[AES256_GCM,data:jIzXDn7e,iv:SZhULBV3sGHEaD6JoHVDYA/9e7eGiTNLxkYOZ6D1aOY=,tag:NZGz+t50eAN2Qgvx/5qXYA==,type:str]
stringData:
    address: ENC[AES256_GCM,data:3jJOVHMuhhiAlF55jZmq6hk9z91zckv8XWqpIrWKphBoakmPN8OSALyYyPf9JAMOozsDdA2eFVZGBVPqZpASMY/anJscX7GMVb/bqhPxafSowILJoO4ZYo0TBgY0duzGjCOBbXrMZKtUmJknlMKAAgMLyAA+5u7YeQ==,iv:tc2Ld9Ik1tZB6pNXyZSsKzUruiEwIwpXj3FXDqzj11o=,tag:WF1zMGKnP84RgzMyRPawTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUKzhha0VwaHA1dk5WWTdB
            K3pSd0FKYWZPSWxvV21DSi9SeHVBSUZyRWxrCmtXWVhkNVhtczk0SmdybVBwT1lM
            WFJ0UHdETmVMV2VBN05tMjQzTVo1SDQKLS0tIDBLemliZ1pERDN2QUM4bUpHUFFs
            aHlscmM2OEE0YW1nOFZGKytIMDZXTm8KNOPDbE1b1EM8TT76FtGku6etgt5BHK5O
            k1MHQ9EXktrtxHG4O9011iO4UNDmiFyowKhdh+hTs8rh48Gac1ZADQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-04T16:02:56Z"
    mac: ENC[AES256_GCM,data:uV9flNH6q4NbT3j1KW+ia7/rLMEiYcPigVuO/mIeuDfT86nzfCehBjVMTNwcudXvxoDj1ztKG/X+VNfQunbKwb5/36PvsrOtisVEtxO6IYPG1bI/WMNqM7kDw2WTdYaNZDcT6bYZWD8s5yE+DM2B879LT4o7aIC7p9PsJ5Tz7mw=,iv:lTTU8nksiTI4isuvV2xWTJfPyAnXcpEtbhcfBWRAm7g=,tag:qkKNqBLQS7h0QWqYS2c1AQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
