apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.13.2
          ports:
            - containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "$(MY_POD_IP):3000,homepage.phoenyxlab.xyz,gethomepage.dev"
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: homepage-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: infra
spec:
  selector:
    app: homepage
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: infra
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - homepage.phoenyxlab.xyz
  rules:
    - host: homepage.phoenyxlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
