apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homarr.yaml
  - homepage.yaml
  - namespace.yaml
  - notifiarr.yaml
  - pihole-redirect.yaml
  - pihole.yaml
  - traefik
  - vaultwarden.yaml
