apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:v1.36.0
          ports:
            - containerPort: 80
          env:
            - name: DOMAIN
              value: "https://vaultwarden.phoenyxlab.xyz"
            - name: SIGNUPS_ALLOWED
              value: "false"
          volumeMounts:
            - name: config
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: vaultwarden-config
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: infra
spec:
  selector:
    app: vaultwarden
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: infra
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - vaultwarden.phoenyxlab.xyz
  rules:
    - host: vaultwarden.phoenyxlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80
