apiVersion: ENC[AES256_GCM,data:j7I=,iv:i0skuVPmZeKa5gSkdsqYSE4zNIurmpq8faV/L91ylEM=,tag:VOKz8DGQGPC1hGfIki5phQ==,type:str]
kind: ENC[AES256_GCM,data:k724S66K,iv:b2zJ2b3h+Q3OvCuNHqqiJbo/Rk50L2+rfBkhXP4GyzA=,tag:TmuVm7njMgoWLKqM6SU19g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7hEfiNBjedc9EEYt1w==,iv:VU8p1xQ0vWG5gqEXs1NscLsfFaXNBxQU0dP9TNXHl1o=,tag:q/8iAN/ksE3s1RpGUnkquQ==,type:str]
    namespace: ENC[AES256_GCM,data:GAIREPw=,iv:RpqeAgka1MUTropdeW2Z801JKpDX6uKGYqP/ngUVzEA=,tag:UagLXUePm8aaWZlCIyUnNQ==,type:str]
type: ENC[AES256_GCM,data:YPTKUE4k,iv:pxjMd28ix0YeRRah/qz+sXsjDbnPyIBT82z/xW97SFo=,tag:mmLhlIAtUBffLzEoIGoRHw==,type:str]
stringData:
    LIDARR_API_KEY: ENC[AES256_GCM,data:sBPEicta7nA2C2JZ+MLRFtU4DsRD1EKtA7lCIxKFENc=,iv:n0CuOOYU+J0nlySieda2/YrUo6/XHp/ymvScB7JZUNo=,tag:2aN7leSL0YczmwQfmrghFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YVRucHNjUE5LdFdIKy9L
            THZmZW9uQStsVjNMRHRhM2k4SUhESEFscnpzCktrRU9DR2ttbzltUEYzL1krcldQ
            RUJwekJNNHB1UGh2S1lkS1l0aHNuU3MKLS0tIFFtd2JyT0I0ZS9XSWcyb1F2aHlz
            UXRlRmE1QlZoRlVjdUJ2TEhvMG9ON3MKKIn9M4W9TZlinZTHtVO6dAJhndLOjjiA
            1ma8GKjb9TFKdQh17bClDUfdusBb8Ps+TsJfWdOB+F5bPyBRUiAehQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-07-02T14:15:58Z"
    mac: ENC[AES256_GCM,data:u0kRjRW/Il+OLjs7aAhrNVaeEgh/33J8ZFfi3HTWcj2sqKp82cvCuYDd0/U414UON26Rr+01lAokDUnPKyVFERktd8FKsBi2A/vOhO/qWEw38Hh3+Y9ZzKXGLC/rTEmENqkC7uHRP3Vu5Ee0AyALpozNPZcJSCrTxNBFDIVdp+I=,iv:pnVXp2FVEv7ir5Kf1jb8JO+DMFXf7B6/nkPelZG/lFY=,tag:C/X+g1sHT8+QUCKAQ63zfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
