apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
  labels:
    app: lidarr
spec:
  selector:
    app: lidarr
  ports:
    - name: http
      port: 8686
      targetPort: 8686
    - name: metrics
      port: 9707
      targetPort: 9707
  type: ClusterIP
