apiVersion: ENC[AES256_GCM,data:c5Q=,iv:kYnJHvSdKcWfbNAxJx4AA4oHb6jRAChVmH7Izqthsz8=,tag:GvbIaIfNcmJ/MDowdVj8mA==,type:str]
kind: ENC[AES256_GCM,data:iuJGixKu,iv:3VheiFzxlbXOYBev3iD3BajgnElZLDEky4jaT7vIHnE=,tag:oHGJmns9dJpBJXqgvzpk/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2owpYBaE4okO7Kq+eZoM,iv:3Bxy+ZfQAj1/b1bjofb5sCUPqm+Lb6EJ/772e2eConw=,tag:FGCy34Dadoo5eoe9RW6COQ==,type:str]
    namespace: ENC[AES256_GCM,data:n7NDHZq9afmU,iv:YZMfq78DZAkvAhxwG+F/erY9DrnAVH1DllyES9aR4J8=,tag:D/W9oam8cTZY8QHPbQmwrg==,type:str]
type: ENC[AES256_GCM,data:v2aRT7JX,iv:sGR1JtkBLHaGV9Cuxf2wtl8QkPPboAyOmbQyaB/NhTU=,tag:6xVUinRTW6QC0n3XSE8/6Q==,type:str]
stringData:
    PROWLARR_API_KEY: ENC[AES256_GCM,data:fUKfwZuSWHT/pqQbyip+2YsTRdBXE3w2euj1Ze9Nfek=,iv:KomaueNh3g93TCB2DK9Od+28RfudI75A9NsTPuUSMwM=,tag:QUQvymT9d3LuENH7UCWgWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WjBlMUNrY1cydlBmTlo4
            cjNrdjh6ZjRjd0FDK25SUzZoNGZ2UVJFQlFJCnI3Q250ZWwvS2tUSXF3eDNUUEJU
            OXNpQzNXQ21iQ3pTTjNSZ3hZcWRkbUUKLS0tIDhCcisrU2dtUGwwTjFYbko1RWZq
            VmFXenU3dmczY210L1dMSUt1RFRKNTAK9qE6vAlTOsmK/R1T4GRD9dk5GkDApQtf
            PLxcmPWt1EEfGZLfpJfw5t18+FP3DVgN/ypBOqw5TK2X1nJx/7OoOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-07-02T14:21:52Z"
    mac: ENC[AES256_GCM,data:/hxyjPtiQlUJOUoA8w5OwPXOGSkeKiEASGdgiy2IMQMmDlPzZ/MahOxN4zZsmYkLbpjLEGflXw8p8yT9baSOnGlw3dencvQQNxhToR2hKHfEeVZTUwzhIA1xgclQmnIWgG1pVCE9k0KhbQpiYf9tcE+H6D6p01wy0srGafigb7M=,iv:F0OM5Hhx6UIS+wi+8kJ7L92+c+vbM9za0XCULkYC618=,tag:sYQri/9EjykDQOqBdmdciA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
