apiVersion: ENC[AES256_GCM,data:yjU=,iv:nklvEIL8MBrmVUirZ3nUipLu3cenOYfp46MVixg8qO4=,tag:DHxT97eOvPwY7QTYjt+svw==,type:str]
kind: ENC[AES256_GCM,data:H5CObEIA,iv:ghB6lzbaEGZQQuysw3au2CqSurMk2GV9erO23aAAFR0=,tag:1ajXebJjUQON3gaxomXklg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uf0bwq5kegvD8OZ3yoyFepH+GM4=,iv:b/zKsjENebbFkiC2vb6zYBmWuvWmG2zPBIKUx6OAYQo=,tag:IFRB70zYrWEzMCD7w0o6tg==,type:str]
    namespace: ENC[AES256_GCM,data:Pc5kr9Q=,iv:a3appp7R7QqRh+tdhCSvkljOZ2Y7kI5OLB0VRGF8jXI=,tag:Rd6kOgwtmKnUk70xJUFgLQ==,type:str]
type: ENC[AES256_GCM,data:OJZddYG5,iv:xcNZ0RLUIh+sStSFEGWFCdJjlX7Q+WOYFAcdKnct+Ag=,tag:ZzSjiPz+c47tc0yTyLZNXg==,type:str]
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:UeRv3QzVnx0o3Ia+ZIz1Jt3znzKbJx7znk3UW4SCJIo=,iv:++yWi4Wj8T9IIP+T2M91sSyHhTqeOvtQs+xyjPtcsfQ=,tag:4/+YuW8xHa54KBJv8QwHyA==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:eyfgnLwF,iv:3muu6KZAnR+09yPAwP6TdtbMG4WfvbYw5Kg9ER8oY5k=,tag:NakNQ2qbTzbaehpfELK2bA==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:nqTgzFrcToy1PloczVi8alZ1ILhKzN0jRZKSPMY/jjw=,iv:i5Xy2LQJDMYz5CHBLgUp5gHTj6e8PGaxD7+HyhuEMDQ=,tag:2kJ9VWdIZCVcXM/jeyWDuA==,type:str]
    HOMEPAGE_VAR_PIHOLE_PASSWD: ENC[AES256_GCM,data:zFErjwDhs7mlI14=,iv:NL4CDRaUR251DgueD0SYmFyVHTuydu2dwfmez/cxKYs=,tag:8tpgqXUYLkZwwlQ38Xyy8Q==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWD: ENC[AES256_GCM,data:5SnXr6Z+0+s7Vig=,iv:ShYs1EFoHQ9C4MYbrqHiA6EoA3dORqJZl44+HlQTE0M=,tag:xgALfVP7dwtuRdErSsz2PA==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:YdY9ezBdAghVWZpbpAjMneGn7Mu4dirqKyYwcBqB6KI=,iv:bOJz/e6IK/d37bnMtNK7Hmm2al2HHqnTn3fVpvm/VPM=,tag:rZ0cD3dbQk8r99ym/bVzLQ==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:6vfxCOit/HcWLySP4pSSig6txfqNe1vtMTlwtxM2Duc=,iv:cINUSOyJ7YBDTadO7P3rkHeJLB2Ywh9ERaz4NzzWRGI=,tag:0zRFfkcS2Fq4t3m5ixxr2Q==,type:str]
    HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:QHWyfx/puy8YaIK4OjERZkYnfhOtugLuI/B+ygLIKn8=,iv:H8QsD/dYmiQkxg5TbQ5AoPdiCpBrIziC33/whHDp6ck=,tag:kyuyrL1dBc9VSIdWNbpvmw==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:TWrujCish2BJuXz17vygRFFf0r/XNdGusJAExDHlY+8=,iv:qqMIVHRJu7XgcT4MDumWUkPMSzm7fxy7TT4SHmL782k=,tag:gKuIYgEXCph+Uz6xvWLxdg==,type:str]
    HOMEPAGE_VAR_SEERR_API_KEY: ENC[AES256_GCM,data:p+V2nO8gUNC8/nFWW/sp5/1uH3qAIJK3NVg56nrxrwzIeXUXGHaFm42NlDAxfyshc4epykuAPtPRKOS6BluTjm12irA=,iv:rekMVtMawlSE/QP4m6JLNa+pfFnZ80vMahUSGp6lSCA=,tag:2wv9PoVuVajCVxy9rqhCIw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWD: ENC[AES256_GCM,data:3dDN+X2CtrbNC5c=,iv:4klPjY8PcZz6cGeYX5Y1Jxi7jYFLIHM2JH0HaFVU+CA=,tag:Dbxie+1v7IRlUM7eK029DQ==,type:str]
    HOMEPAGE_VAR_JACKETT_PASSWD: ENC[AES256_GCM,data:h/7ns6HTFFQ0GqA=,iv:UDQ/P/b+NGsDtfmQ8ZRlWQ7qfYPput8r5X6f1oWKEHw=,tag:BwAiMQDdzLSBD06JnBtC1A==,type:str]
    HOMEPAGE_VAR_FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:66bo4KpyXpnTXlI=,iv:TtuitRpOUXAf1kJx83FHrkX0AR9FTDondRPkqxeH4Oo=,tag:bNVJ8mynF8EgnvxNvIztzw==,type:str]
    HOMEPAGE_VAR_ICAL_PUBLIC_URL: ENC[AES256_GCM,data:qYL9iI787WomIq8GjGrEZR+9DYhqnKmbF4bcjeezCBo1SaIhbnnwD2yA/0BvSdnlhlOr2Z32EynsNX944MhLuc5N7DKGhiZqCnrxmhsaJtiviw==,iv:fFqq+2WhmVhODzaqgWCwyM+4po17veEdxHmB/BPwh1E=,tag:DIrrL6fMojd4sChGZvBAjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc0FLQUw0OXlHS2dyU0tr
            T2R6cE5tTUJXc2xJY2lJOGVFSnJGWHFERjFFCklIemh1V0ZmSk02YzBHem1iYzY2
            TDNocFVZUUxxVFEzNFlrOSs1OEJJdmcKLS0tIG5HeE02bGVqZThYSHNYU2JRb05r
            WkFZam8zcmpySlhDVm5YdlV2TlRPbTQKGVSJwAhJaj0XLpeNkpdTcnUy2FsIRFQ7
            9Kr/PahAyVQv/OIMxytu5V0ajOyqQu0f1yVUo+2fMObQDAaAXJQC5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-22T16:58:58Z"
    mac: ENC[AES256_GCM,data:w3HGx54GbeDqZa2vPCzxKvyttTqBsdBf9eHavOdFEQcEbga+5N3CLIF/RZVB5F1K7fEbe15fIsCRK1PKWIUS2ZdqgYq5kMeLUxMDvtfybC5t4aDaK42KQZs9aPwuryHRz613/Chbi4+K/hR9vRx+SIni4BgFz2olib4sZnkKdiI=,iv:A5x9n5x+M4lqZJPo32p2XOuou05xYLwXk0oqlMLq1iw=,tag:1WThkCrxb9K/FxC6d/xepw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
