apiVersion: ENC[AES256_GCM,data:rXQ=,iv:z8pdUNEEN0KJ9UZEbQ4EgalEYWOapqAxW8k1kfgnd1A=,tag:t1a0yUSJPpi7kPUR1hUcmQ==,type:str]
kind: ENC[AES256_GCM,data:XtvxpRao,iv:pGcqlVr+ExQua/AemELPfHHxu1Dqb2jQ+XSAiovZUZQ=,tag:ru0g/iYBZ+ttWSld1cQ9WQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JDziGQOurX8h0HyVzJ71odQzWMs=,iv:aYP1whVCMyYUm4UFrlUn3ZBuqHQ2iPv5taWR6/PhNF4=,tag:5ABwJDyFCoM4gRJeK0NrNQ==,type:str]
    namespace: ENC[AES256_GCM,data:1H68efE=,iv:/wp30E9LiD/SpIaOh43jwnpLT4vUiW2j2opPn4TO6lA=,tag:czCFHWXfFtBAJAhM+YRDbg==,type:str]
type: ENC[AES256_GCM,data:fNEmLG9r,iv:1/GcnQTlV8eAmaLC6vE/gM+nno3v0yE7Ydg1NKQQup4=,tag:9PEDgwrT1ixgR4dmwlUDCw==,type:str]
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:hr4+vEsYfsJ+gQ5XlQgJ3ktNlQiN4FhfrnAle5JF28M=,iv:TZ4KW/KAzsZdg54Ss3i3iCUhSH5kd6/iDiX9zC0j1Wg=,tag:kqyAf69qNroV4qPUBbPbVw==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:CmgRUMKe,iv:tnirT2cj/4G4ZPGdpjfrKWFjGxEJrF9tl6d4hnE60FE=,tag:SwtY0P6Oc1fXPIR/suct9w==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:nivoGZs/lIhp1jw3tJzD4YWDhL5ZBxJvU3JMcJ7073c=,iv:r6vujMJZVW+b2nlTY8FGk0Vz+H3yzpSE6Al9E9iPOX8=,tag:yKqdhB251ILeVuOGIlMX5w==,type:str]
    HOMEPAGE_VAR_PIHOLE_PASSWD: ENC[AES256_GCM,data:YdQznzQIrJiBZFU=,iv:G+wLc2NnmT3TXI/BF0Oim4vbYmJL4UDLT448ohSHUGE=,tag:WAcbsKeRrYiRXRM26I8ISg==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWD: ENC[AES256_GCM,data:QsK/KBnOPs1YrK0=,iv:wrBAHt/A2av1F4RqIaS++w1a/DLsNkD2bLxWf5YTydY=,tag:6/PoIiu1onVrOKM8vaG29A==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:9b9K3UU9nsmOFirHpu/9DlOkmtuCUI0eA3APFQrWJ6Q=,iv:EhTD8ZDHgCukYzODtcqgyO9I4UWUltoXbu2er37P05A=,tag:ti/2V1kgK8kq3xi+y5ldXg==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:raSq4hschSnLfdBfMtlWKkTTQrSp+gDINVoIDJQpVqU=,iv:2qzfW7Vw82fScojc190wxZh0kFUz+CVHTMVjiw4u0p4=,tag:4pLpOgeyTXbOgdX3Es9OEA==,type:str]
    HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:jbyiBTM9BuHokANbhA/XJpwtPId/lo34PAOzRKbcfaI=,iv:qpuE6ONDhbQqYMeZeAaJNT8C6TA3TLQEmioA6IylcOw=,tag:8iHljp4N/u4+Dt7c8Rintw==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:xm7JnqhxnXKUDH4OI1ryrXTGtI3lOxCAYSIwSf1rglQ=,iv:VVAEJr4gf1R7uW9YMwj6TVh6+1EDNxtdaavPOqGEkYw=,tag:t1zmIHVefJF1t8fUsFwH6A==,type:str]
    HOMEPAGE_VAR_SEERR_API_KEY: ENC[AES256_GCM,data:vj3l5iUhSlgmpUs/QlzYtEQhvEF13tPBP0YdG79IBXJTQnDnfqcRXANPf35OW9zEQVfqrqzrUBoZPNpcw5nNA4jjO6g=,iv:G0ZJla+00EiPaDB0h4KGEOw1QIe1xSzpe/fKg0iqtyc=,tag:K5KFhwkGOCzEYn/qSOvIdA==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWD: ENC[AES256_GCM,data:Cjiv+Ql3MvGE/hI=,iv:DOvztcURMgHUso7Io5OQz2DTiUyzGS8Tv/pERCMoAks=,tag:rEYpuVzQ8xpkh1wZiLJAiA==,type:str]
    HOMEPAGE_VAR_JACKETT_PASSWD: ENC[AES256_GCM,data:nhkRcAdq6FgLGaI=,iv:UVAwwq62XdRdFmbFoAYQqS68p1+qNcnSqN++CK2C2Ho=,tag:HtaLKzpLa6pdcOz33kI/iA==,type:str]
    HOMEPAGE_VAR_FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:Nj0T429X5gIDsbo=,iv:tWg1MUCGRm0YjQqi4y12GNoMOBJKADNXh8FHRAA1BK4=,tag:qJGObExd0DQwPoU11boqig==,type:str]
    HOMEPAGE_VAR_ICAL_PUBLIC_URL: ENC[AES256_GCM,data:FIM02py07ZgIJyXAWxLnYz3SX2j7PU7nvf1/t44mxP5pncSjAQvjS9fwbu1YWWD3zO7JP6DuH1zxvnuxAbSh8ZJpDpemN3c/Y8YNAcrzo7LX3w==,iv:Rs/79uMNQ/7SRicfY8ZAuIHMv9K664NKogjfxS2+FLg=,tag:pRez1uW5fMeQlQQY96z/Rg==,type:str]
    HOMEPAGE_VAR_SPEEDTEST_TRACKER_KEY: ENC[AES256_GCM,data:7uSqqy7RVXHhuZKje5lmn1yVDJyAdEXQ3UdYfQfY9eRLT4jCw9tY/0TwWpheRATv,iv:cBJfcegzZ1wJ36t9HqilqWt/ucV0eUVYCKtRMOHFM+E=,tag:0+9NqBEQnsKZ3u8WWaxYVA==,type:str]
    HOMEPAGE_VAR_WEATHER_LAT: ENC[AES256_GCM,data:ERRNBRiDOg==,iv:FyaOjGzx2ckHqjfj/WnqYPi4SYULJXGyd9PnWtCVnBc=,tag:b/aCbb51Y25rvzWGgGLILA==,type:str]
    HOMEPAGE_VAR_WEATHER_LON: ENC[AES256_GCM,data:P5XjqJHcJg==,iv:kdVxXYiTwmmdbxm3rOXVx1Rfju8Ivk6YX2rsk7oZJCs=,tag:tjg7hsjfEAzsiCyx6TVTcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcXdMcnFWVVlrRVNEM3B4
            VlBZeThxa0ptZTVnS3ZKa1VjVHBVa0thNXprCk05TVFhNk42U2UxbU9XdUNaZTd3
            WEVYcGFLLzYxN29MSTZGa09LZzUvR1EKLS0tIGJZV0lMc0NCWVhCYldZaTdJTGxB
            MjN1YzZMSXM1L2czVkxwY3BkVUd2STgKhBgNnY+ewxl2SHWcP2xza+/Hc7iHMqln
            zCLhm13+3UkmflRBd8+PHzfJ3+9vdqbGn5hXJZLqC+DjQWFG0lHQEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-07-01T16:52:57Z"
    mac: ENC[AES256_GCM,data:PtiopIzbnKhU1+cpWY9KJj+3OdiQodSN2gOisfP5PP6PX6n5lrvSqY8uIbi7iscsb97/hgEtq4EXh53hgHMiPgSfGnKkB7yI72+BPsqDaDR9EvJuIWuTNUqsc6rUnBjKk290caSUMIpQ7oPeMcKP/yTccMNxYSQ4k0HhUURDSIw=,iv:9Kb1llszJx8yR8lT6A7kdGY3+9ins9TcD3KSmjUaTso=,tag:36q37Y2PWXlyI9vuITzmOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
