apiVersion: ENC[AES256_GCM,data:h08=,iv:1aFuLUwvCGDKLa/FkZvA6JJDB7tyBrZA4V6B99y5GNg=,tag:5hNwkjJqOQR9y3Aomtm1gQ==,type:str]
kind: ENC[AES256_GCM,data:P0qorS6t,iv:J9p3TBrVwnDDINEwDgOsc9aTkL3fh7c7EAm9s1iQT/k=,tag:rzDZPqeyWFPDE1tN2e+Jsg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P9lzJIesz8OlUuRgSq6Ojx55OZQ=,iv:Z0KKaT/0dXnAn8utYdvqLQRjdht8paljeALOz+RWCSI=,tag:GgMKXvlPlsSSYARrXQvUuA==,type:str]
    namespace: ENC[AES256_GCM,data:yBd8TQw=,iv:tSEeaWwlj91jt+pdhkRikqjaAoNaSg29y1qdhRqjwKk=,tag:UfLzanP19+7Rxm5ejQ/VGw==,type:str]
type: ENC[AES256_GCM,data:qTbjrFvi,iv:WjiuIdexlmklfuHE4Prr98uyQ0dLtz4RNYmBQvB5AaI=,tag:ePjkRFD+bftExVpEv3m/4Q==,type:str]
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:o2c8ioT1x8n3d0JZFS+8URxZyYZ/Tk0nJkfvie12Oxo=,iv:qNAK0AFJ+1vw04gH8PWpNpvzKhrmE3rksX2+Opk6mcY=,tag:DfDqdEVvDlHk+BG2CY/DFQ==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:H0jbd2Ni,iv:bXUHWasz/TWBj14CwNDVU0wA3IqABQm2LZCCR1gNbzw=,tag:+M2JemAAqPilBAUleV4rNA==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:dexaUWGKfYUyOX+/EjxozDnl04Rz9RiBgCCuSISRivo=,iv:V0u7isGhSxn/KEX5txDwP1+n2moO3bPwg8lWc18RSn8=,tag:Y/URX1aSmydd3KkP3dmdBg==,type:str]
    HOMEPAGE_VAR_PIHOLE_PASSWD: ENC[AES256_GCM,data:r51jpFLOojYCFN4=,iv:Hdo7TcKa02loKUsz9wywVYVjXY+9T99tJFQ6pl9VNWU=,tag:ZRUKwsBvWoAJ4MS0WEb2MA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWD: ENC[AES256_GCM,data:9z6xX2wuerPiDIU=,iv:9mUaCRNl/8BjNZ54ggCl5Qn7PHO4k3c0MelJQbtwsFM=,tag:DdK7WafcgZiR7rajMDBfOQ==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:C1Q4djjaYnplHUKmlB0QPZdd6iqzoQGyJiNXMybUriI=,iv:dCYjp2VhPNlmicmKMCP3Pv39rRX5rs6btuqD6c4nhBo=,tag:Y1k2ECsGxpqRMiGLFn1XYA==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:5PAFvkHbZTSAY4+wX8Bpvx76rY02pxV3CXbxExrZ4FI=,iv:kZS9Rm3PhLkP2HcsNcYoQayzzVuyHBkZ5KXzvPoHlow=,tag:SodEmtj/FSasq5nJSILfow==,type:str]
    HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:MPOsR6Cjf4UxMy7y3+0K68bKpv1kuUainyy00q++3rI=,iv:iJzURL4jR/K/vf08eebFrm533ObHY5mr3nVcACuT1z4=,tag:QsSgaIeL0mbw9lHE2m+3dw==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:qmpJRBZbbif18MUPJrWjWsrjbvxFTZfp2xUgpp9+8ic=,iv:Oqu911dSFuW2uoENg4rHikhBslkUnbRMtVZ7p/hvWVw=,tag:fHwxxK1ZYhAfQGe+YItxnw==,type:str]
    HOMEPAGE_VAR_SEERR_API_KEY: ENC[AES256_GCM,data:vWSIaasOUZtV/wzpH/sEdcxsSQGgPPRUChBHeUAfqxqUAq8kCMVB2SszGmImbO6Pky+/vlu8oSBSGfZ1GLnLN3t2EbE=,iv:bauyndNFZd7zHGK6bdjlFmwURl5mOi1g4KZKjZLVmMg=,tag:+ygky9RM+4yMZS4KmXIJ1w==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWD: ENC[AES256_GCM,data:cw5bn2Qj5fxK0aA=,iv:ggdY8PkHduOgsJvzllhE1qhoV2ge8b88U6Sw7Zce8mQ=,tag:xojFMKyjsb/6qLsG/2ExbA==,type:str]
    HOMEPAGE_VAR_JACKETT_PASSWD: ENC[AES256_GCM,data:NEZtg1IY/qURPD4=,iv:9FFwrXSzvqBxr8kapZWMs+8l8ecB9J326+oR0Gh1q68=,tag:l+FV0XzbzQ0euLe0S4zTqA==,type:str]
    HOMEPAGE_VAR_FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:mgffCz1+Uat/87M=,iv:XpAOEruFMNJvSBkI9C/gygimDNHCb1junY2a9HAxXrc=,tag:jRCuaCt2YgdXOpHAti+x0A==,type:str]
    HOMEPAGE_VAR_ICAL_PUBLIC_URL: ENC[AES256_GCM,data:nVd6sjAH85L2C/7aUjljhP7cmSij3aW3L57Xi21pohc2GsavkZZxQcJof4Pqdmu4JNoEzYe4DmbajeM9bxSep5kdqSrpLgZSMJ83vuzJF9XJKg==,iv:2vSPfse5wetG+WPfSTQ1KOIOPERJWffdp4oku99HjgU=,tag:yDY5wjmmixFz8O0U0M8/MA==,type:str]
    HOMEPAGE_VAR_SPEEDTEST_TRACKER_KEY: ENC[AES256_GCM,data:Srmez9WK1cNMaln8VIFf8QYJN/IQxxIR5U9qBwad4kUcS2CJw8hVtFJrwcMnVb0t,iv:m/QXKOEQjrnDc8fKwyZpOh1pLvf7wwnpCFEB7C4ciDo=,tag:I2MYDkCgcq+lLcz3qD62oQ==,type:str]
    HOMEPAGE_VAR_WEATHER_LAT: ENC[AES256_GCM,data:8WargDRtWA==,iv:rtRansxCawfL/DkplEPbq/TfYM6nnuKhoE7zvoPAm+4=,tag:h0tH2wHjeUVomKRVi2ZO6w==,type:str]
    HOMEPAGE_VAR_WEATHER_LON: ENC[AES256_GCM,data:C7Th09IehA==,iv:IyrfbUkb1gIGC/rGE/M88ZJ16KOtHcp586BowYCOPUg=,tag:OS9o5NLqOietc4mAkhTgDw==,type:str]
    HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:TO64MX2uh/eH7SP9LhRw+87fwhCNm4UJHpvxhEGzCKA=,iv:COXcFO052++/TshZGPDIKEAKKmZNvhuQcggsCLqJrNc=,tag:Aw8zbK0mPlCCbbd8fjcc1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS1BvMjJmYWw4dVUwQzE4
            VlJNOTlTVWdaV1k0Z0poS1JQSWdXbGNET1NNCmc1MTJQMHpJNzBSdkpzc05POVc5
            eFZWd2FEM2xPdjhrQXZZRmp2UVhxalUKLS0tIDQ3T1RSb0ZxOEpTVU9LWjY1TzZG
            NUliRmZJaUV1dzE4djJuNTdJMDB1SGMK460V/xp4Jxn5uec4hM/7vQHRrFDiTVC4
            YoanAERW0Q3JGU3JBZ5M5ow5cUeYTe3BE/stN2cU1FffO52puVeOuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-08-09T08:24:05Z"
    mac: ENC[AES256_GCM,data:DHoLglQ0Pfa80l92U6ZmC3QkHzvJqpvKhbklBfOZX3al8j1awaGJdVuIEB8d83IBqOl1dqblpC221RJM38g2yaF6GDF+dQ1xjG5WrN0eNtjtToDsz+btIpN9MnRjtBMxmV+oAFaRkP4GRrVP4tXiTEbw8Lezqv16lDUqNI6Xs54=,iv:k+qVMSrDacDIdd5hu1dn9HM48nkyX6JCeMIrEgm4TCY=,tag:FlyvKmuX6In+hm59BEXNVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
