apiVersion: ENC[AES256_GCM,data:5yk=,iv:4WioNzI6LcPkpqcU7c3/ISkpzvVAbcR69c4/R6SeXKM=,tag:uQhR/VtUGJmbN7EAVr6BeA==,type:str]
kind: ENC[AES256_GCM,data:25YL70nG,iv:JUEUlvMxCktz81hQFKE5pK+6BKpceB3kgt83aU9g/0Q=,tag:0PSi1S8Tr3BBE428mHUpzQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:o3YIp312hCWeBdpuSw99i1+ALoA=,iv:ofjS53aAv1hDoQv0Y9t6VmiRr5CVaiATIluJJVM94JQ=,tag:gPyTf+iUnOmsOpkV2M2aRg==,type:str]
    namespace: ENC[AES256_GCM,data:TSr8hZk=,iv:eXsF67kKA0sLVRtUHtHuAVN3wrj/RxkzJSk6vYlR/Oo=,tag:cDvrmmHfO8kulsFyK6OwWQ==,type:str]
type: ENC[AES256_GCM,data:NRfNs5cx,iv:RlXXr2In/uFCCLwLwbJ5u1ScuP4EXbeh4u5GYot/YXM=,tag:MMkDkVUNqlS4i/Ek49o0Dg==,type:str]
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:hXrBQLFZkoTy8QkujjVVKZeaxENouKUqVJVD1jgnIQc=,iv:Bj/yFeDCDGjZKCHXT4GZGFrOA7w2rzEv1DBlWqDpC1c=,tag:PgYvuTZLjQuSbf4LUPZ0Hw==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:3sBkglnQ,iv:Wu7NLYHG+nCjSBOTaMggDl4ePcrC77y3hewn/fEUjyQ=,tag:TKy8ampYZBkKi2lwYq1O6g==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:8MUkCKBEjSVpBWjBMwJXVmHHSf6JH8rnw109Bctb4pU=,iv:xLuS9vBAanKaHqyT5L9I0M52jv/Gwg46batx3ONZ/u4=,tag:9pXkQLcqT12B/1mbQV6tNw==,type:str]
    HOMEPAGE_VAR_PIHOLE_PASSWD: ENC[AES256_GCM,data:2mPwtI6Mm++PFd0=,iv:L3WC9bEfMVVbgQLFQdtcc3uVzbAdMWuBAdEcxmc1Y5Y=,tag:LRVYuQ1P+HfFoIGt6NkWkA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWD: ENC[AES256_GCM,data:dhIzqXsaqgYRRss=,iv:n1mgPAXwE4zfLXwslheRq7+R94Wg/LqnXnO3M3BRn5o=,tag:Ho+RHwPhiqDVaY/Lag4ADg==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:KHEbRKcFSqMopVfax5Z7cTXaUzsInGWYnSTcnkDZEXA=,iv:qeIU2fLuhSFMUOoLlRctLu3fbVPAD9shsQVYurmqD34=,tag:NUnvh8aiQvPkiW9b9lcfjw==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:aiDXHd99/ur8ktD2S3Yu6BN4+0ycbu+39SjCHoMfw7I=,iv:QTRBW05Scpa8vAZ0tDvY1LUYbvDvv4Ho7t7oloRD7hA=,tag:7APUHHHLxy7T7v/l7hmWZg==,type:str]
    HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:yLmsoxrWqyWG7L0uVjCrZablfqDFxGXYXMT3Yh/UWRo=,iv:OAy1oxeW6VBwmVL/AxR3VqiRAKHF7EMEh+J3KdPQy3M=,tag:9d5zFpHWfHegjlg/OImO2A==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:qN+oP0kehUcLRc7o9IzT9vwf3MfqEDVQbqHD102mR7s=,iv:je9wgZRVj2dSOux4ljDGhrTX9qkwmU00USpHjurEMyA=,tag:ntwBSYRXFaSoNiZEoxe6Zg==,type:str]
    HOMEPAGE_VAR_SEERR_API_KEY: ENC[AES256_GCM,data:RXY9j8J7eBT1uKvcL0JgeLigdlbrHjyq3iix2z+X0/jxUshXQJAEHjigvvWel8F0i97uwTb/rH70lf1GD5X+PcxRCOw=,iv:PLpAzG0L+pDNaSvpBtEXQSeY9OqW//HSUmFeCd1aAYg=,tag:t4+muQtu889yced1d7inqA==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWD: ENC[AES256_GCM,data:LYvjsYdlqBLuB+Y=,iv:K8AFkCLM8vJC0/nRMEsxlyYbuKSQCwFR+ileH0q9UX4=,tag:4XkQan46yyUUgnAq6I5qmg==,type:str]
    HOMEPAGE_VAR_JACKETT_PASSWD: ENC[AES256_GCM,data:QMsSIMpUcgzhbjE=,iv:HwmBnphVhgJAtbZmgt5uqEcnzj6YkAopL38vVZJt4hk=,tag:UIuEOwkLop/9j6WPWB4OqA==,type:str]
    HOMEPAGE_VAR_FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:0GVrMvAYzaYrXxc=,iv:hrABmsJz3JPmh1NpEfQCdHDdpIs+FBthg9ZUhdEOTgs=,tag:cS71qm0XRudeNIkGC9NDmw==,type:str]
    HOMEPAGE_VAR_ICAL_PUBLIC_URL: ENC[AES256_GCM,data:BRLASHVBl6hF/M9jrFrY/AN0SJmSLxt310dvddAc/lFkkDX5xqQ+WlTwmXxWop4dCRfbCRs2tFUcVlL2nKXLh2NEGnH6nLA1hNx0AY0oB5T7sw==,iv:yDNH6jGeuBYpJGeBjcWjUDNuhxn8UkGmGn3mnJyn0f0=,tag:wNIoIF7RHIbPQGfFyU9Grg==,type:str]
    HOMEPAGE_VAR_SPEEDTEST_TRACKER_KEY: ENC[AES256_GCM,data:WXZCA9dzaNVIhU9wrGit5miE8UNmx6M02BtqAXO+di66SrOy3LmLCMIxsaXfP6tm,iv:vIxh/8gk8b/Bv4HMqFLij/y2S3V0ks9/aHfF0mWkqXE=,tag:SOdXK18F8V0NeNfPfA3FTQ==,type:str]
    HOMEPAGE_VAR_WEATHER_LAT: ENC[AES256_GCM,data:DQfA+ymRYg==,iv:mbPLSIxzFDrD/zVzkIj49+uuS757iDpbo89o9dPdb0Y=,tag:a5uFc8R+FvhQ22JDVfyy7g==,type:float]
    HOMEPAGE_VAR_WEATHER_LON: ENC[AES256_GCM,data:IBGpycE/8Q==,iv:4tm5fvRTIiGsWkzKbbMdtK/J7HZYLrZeQ0nNnHMdlno=,tag:Pwr1koJfFRvLuJfV7vofbw==,type:float]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTFc4RUZBMjVyclN2Z3BG
            d3N1ZVVDOXFocVNHUTJpRFE4bWRDeDBJalV3ClZoaGhkTlRoVW8zWFFPZHViU0hj
            bGlOMVBMVzd3VVFtQ2VGaS9vQzVVNW8KLS0tIEk2S3FieGdoMElqcWhLQk1VWDNq
            Q0VJd1JLWm5sdEprUTBwUHE1V2pXVzQKHgGkKCeMuLXXolVqmgKJ2h82oknlp0pG
            77DNG6Oq6ZbN6Q3GEW4IxsxmJ+fHqpe6hEtky7RTA85VpE9Ur4jqAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-07-01T16:48:01Z"
    mac: ENC[AES256_GCM,data:FzdqYuvLnG+6c6wuFEqDMc8WUsInkWEDN4+oJWhdR4K/BWY+oVBX0lardKPaXwgZSH0wO6+cXvbh//thviXAiOpzaOe+b5zFrtU07WkE3AT7Wh5Iqfo4S0gOrMQ8DpF5kl2DC4rNGr5VTyhkjwJc1EqE2hN+U6uj9bmPpL4fENs=,iv:kLHQnhFbivjuLQmnW+8jiBx8KDcco447b+rfSxm00s8=,tag:TABQw0Dgg+VQsE8Fy97uWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
