apiVersion: ENC[AES256_GCM,data:wCo=,iv:/RA1QU6pyU1PAsuTJw59KJZU6ocGT4QZNRwHH2udQ7M=,tag:faB2q/Z1vEmp/hZkg4BBgA==,type:str]
kind: ENC[AES256_GCM,data:CNGcXm4H,iv:SdPykFTWs9aGIYOcS1weptP6GuKWqUuHIAlLjDUTxro=,tag:yjw/WdUaduGjI68fT7PsLA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1C5dy1Cq1MfVGIMR1MoZcwuC,iv:VlXTHwTz9n172jK6V23QLcE+oRki3DPB3Kk3BNEsOLk=,tag:qYEck2Jm7jKrHspV9QuiSA==,type:str]
    namespace: ENC[AES256_GCM,data:wvY1P2rwayz9,iv:q8bwxRtWFrcWa7Lcnv37p/CALA0ZoejRBZc9mWlv2lY=,tag:4WqSIZtiNHVjB50qe/WFtg==,type:str]
type: ENC[AES256_GCM,data:yaHzYK94,iv:8vdn11qjd3Tpqe35n+1rssthGgTtfiS33hQthABbuS8=,tag:OUZ4lzjjfMoeuZxYdrK+tg==,type:str]
stringData:
    QBITTORRENT_API_KEY: ENC[AES256_GCM,data:90z79fGp6vflWtK4d0nAA1lZKmpgR/RQPWrOvMY6KR0=,iv:nARMR0R+Ipq/aoyggOti+OC4rpWY0dwZz7QrW1I10TY=,tag:rpuIgMoCV6HQ+KmUuaTL8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SVdyQUdva3JReEZwVHFE
            aEJ0L3NrWElOVWZYeFFCZjR3SDJhdFRwbncwCnNMM0p4M01rei9LTHVnQ2xwTEto
            Z3lYWG9kY2tFTFVNaE9MYnNuZ21yV2cKLS0tIE5Udkh2MkwrcDhEWldyWHNDb0Rk
            U3BLdVNVd0p2YlNwOFlhSmx0dzFja2cKeHZylbJOpn6l6z51pmI3LTgJdykx7n6b
            cvlVnOOo8yNFtKdyecQwK29ZEtPL58Umm0ZKT9CVxo5phDtCblFGEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-07-02T14:38:33Z"
    mac: ENC[AES256_GCM,data:oGeEHlneRfe7gJorxAPZRbUFbIpZbXbLFxO4Jlb2TychPMSDzKO4b4F4GA4ptU9QOBK9M9wBOnedeeumLYGpODAHWSyyQVBMKnr8RR9SeaJisL7u1rKVjAb+xmKQZ7HZ9PyLiWqx7PYmExgjJVLyFf5kiJHFA73AbmJyovWnLgY=,iv:RuaDH6T4ZgCF10TEh7kTDQn/C+qimzdMuxqNwPFAsLo=,tag:HnxwXH0LLbxBqfCiPg/ajA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
