apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - downloads
  selector:
    matchLabels:
      app: qbittorrent
  endpoints:
    - port: metrics
      interval: 30s
