apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.32.0
          ports:
            - containerPort: 9093
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: secret
              mountPath: /etc/alertmanager/secrets
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: alertmanager-configmap
        - name: secret
          secret:
            secretName: alertmanager-secret
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - alertmanager.phoenyxlab.xyz
  rules:
    - host: alertmanager.phoenyxlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093
