apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
        - name: navidrome
          image: deluan/navidrome:0.61.2
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: config
              mountPath: /data
            - name: music
              mountPath: /music
              readOnly: true
      volumes:
        - name: config
          hostPath:
            path: /srv/k3s/phoenyx-media/navidrome/config
        - name: music
          hostPath:
            path: /media/music
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: media
spec:
  selector:
    app: navidrome
  ports:
    - port: 4533
      targetPort: 4533
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  namespace: media
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - navidrome.phoenyxlab.xyz
  rules:
    - host: navidrome.phoenyxlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  number: 4533
