apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring-helm
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - alertmanager.phoenyxlab.xyz
        tls:
          - hosts:
              - alertmanager.phoenyxlab.xyz
    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana-helm.phoenyxlab.xyz
        tls:
          - hosts:
              - grafana-helm.phoenyxlab.xyz
    prometheus:
      enabled: true
    kubeStateMetrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
      hostNetwork: true
      hostPID: true
      service:
        port: 9100
      extraArgs:
        - --path.rootfs=/host
      hostRootFsMount:
        enabled: true
