apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 30m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: '*'
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: flux-system
    values:
        alertmanager:
            enabled: true
            alertmanagerSpec:
                secrets:
                    - alertmanager-secret
            config:
                global: {}
                route:
                    receiver: discord
                    group_by:
                        - alertname
                        - severity
                    group_wait: 30s
                    group_interval: 5m
                    repeat_interval: 12h
                receivers:
                    - name: "null"
                    - name: discord
                      discord_configs:
                        - webhook_url: ENC[AES256_GCM,data:sF2bIdA/+iCT9s6mH9ZLFhtYjthmIm8EUm7dcjssymbVxHq6HADNmB9hTxt7QGbJ/XvVQEVzf89qYnArVtZkttU7g8QQ2S/DquMpcAlbT5sSLGckuCogxRGsC/BfRSPD9m2YpDShItnup7qepyhJ8olM0kNHH5UO8A==,iv:Zccv0dYPC7Wym+X1GCA1IBNgsmucyfWVWM/EUgSlSQ8=,tag:ibtG1jdbjCvOnnjqJnUnnA==,type:str]
                          send_resolved: true
                          title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
                          message: |
                            {{ range .Alerts }}
                            **Severity:** {{ .Labels.severity }}
                            **Summary:** {{ .Annotations.summary }}
                            {{ .Annotations.description }}
                            {{ end }}
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - alertmanager.phoenyxlab.xyz
                tls:
                    - hosts:
                        - alertmanager.phoenyxlab.xyz
        cAdvisor:
            enabled: true
        kubeStateMetrics:
            enabled: true
        grafana:
            enabled: true
            adminUser: wolf
            adminPassword: ENC[AES256_GCM,data:rQKjnjI6SYiETIY=,iv:M9UXXLITtNuUeN8CV5uhmgsfFHFzGd5Dh8SFimgb1Ts=,tag:wvabutlovmuu10ND9KpokQ==,type:str]
            persistence:
                enabled: true
                type: pvc
                size: 10Gi
                accessModes:
                    - ReadWriteOnce
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - grafana.phoenyxlab.xyz
                tls:
                    - hosts:
                        - grafana.phoenyxlab.xyz
        prometheus:
            enabled: true
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - prometheus.phoenyxlab.xyz
                tls:
                    - hosts:
                        - prometheus.phoenyxlab.xyz
        prometheus-node-exporter:
            enabled: true
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjenI1dzAxOUVMY25rWkJQ
            YVExV1dZSmZhblNZUzhrNjhYMms5cjRiQTFzCmpvZk53M2hPaXlwSEs1enRhSnVF
            NVB5QlNmQmwwQkhsWDVCNnpqWFFSNncKLS0tIGs2cVhFM0Izc0J5Tkg1UCs5eU15
            WWRCS0RVWTJ2WWlqVGlWQTQ2ZmVFNDgK9tInP7mWyz0b7t8hgGapJ1Zs/mP8Iks5
            13aFyOiha71gHs3JBlkgbZuDxuc1h0sqUMJnM6XFrj0Al0PW61UmKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    encrypted_regex: ^(webhook_url|adminPassword)$
    lastmodified: "2026-06-27T16:18:32Z"
    mac: ENC[AES256_GCM,data:+PQvIbH6hRZgbgnS51UD1UPlpigXxz3sA3UznIuW39Tl/NNBr/vCdxgdbYY6FPoGTmv7nqsjhkjsipByDyxRciufGvJwi6oDAYtbWGgYv+UT5WJBuHwA283PgFjyiN8rqCjsiQQ05PcHW7kGXX0xn/uuKbV3bVHWp7hmoXGsG80=,iv:hoGL1q6S6p0zX2FLeJr/zzJLqTAOV2+ix7bkh0fBjAI=,tag:QWUeRBtyTcJqP/Nzh32oAA==,type:str]
    version: 3.13.1
