apiVersion: ENC[AES256_GCM,data:sns=,iv:EIjM03TgtOj4P8bF6YlsL0qAgq+zE+6zlEK41IZkY9s=,tag:5usQKYJTdDUXR1rx7so9Wg==,type:str]
kind: ENC[AES256_GCM,data:ZNuFKVx6,iv:D/AHv8h8NacfbMzmjfM9+LxSRTz1pj0DPC58k4x3HM8=,tag:bcMkKNVPw2UPzs1D3F9qYw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w9t5QtOUGjbppTAOnW297Q1hvDykv45D,iv:9/R30ZhMJThptnQQifG1YMMcyrFP8RJ3T9ETZRGc44c=,tag:YA/ERSlHan2V5WlcmkBMzg==,type:str]
    namespace: ENC[AES256_GCM,data:EKgR3Z4=,iv:NrPP3J0Cdowl2breiP0LsF4VHqLE9CP3BMm6NA603/A=,tag:RpWEa0UdBDpy/ZnLxHBAog==,type:str]
type: ENC[AES256_GCM,data:+qv7e77g,iv:w89nJ0/Rkpgfx8kZSf6jZl6+LjRQj+L7+v8TJY/CjL8=,tag:ciGaB1wyRhBNhJ0HEOoP6g==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:33mgn3xPBxO4fU0eSrtfdaGPazIYpjr59B7TsuIUoag7PfhBKWFkYcutqlI=,iv:ErrHwcmok+DsztBdN4uvyZJq/0xRWxsAVJBO3Dy1IpI=,tag:ecMgmnvbF97VgzUX3b1bHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeW5pRzZhd1JaSE1seitI
            R0VoZzArRWlmdWFTekp4SEJrbEFObnVvNDJrCklMRGZvNzUrd010cUYzS21tRGVr
            blpoWTNTOXd4WnJ6QVI3L3J1RnZYOUUKLS0tIDN3MG9EZVVuM3RuNnhzWmNWQU5C
            K3JuSnRubU5FTEVBUzNUaUFUMFF1NVUK78YswQYom0Yr78p4HjJNJ0yy3gLYlsRF
            9TllQSZi+jjtFQ4mLTMk4jtlF2aznjj07DDyAKdbkk8CAj6YCsszMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-07T17:03:59Z"
    mac: ENC[AES256_GCM,data:Mbqsd2mL6xZLdPjH3U7it9VmaH0mfulUOkcgHZkVSE976qezfV66clokJ8SfABDAnnzImodIOK5zvDIHoqOIGkP8Sp94+QygVc9Vl/W2ZIslhyq1/MbjhRiEwDbiPiGuvY6leSf17sSvnI0UrzvdhmCzu8cUngf6DJN0zmca/p4=,iv:/5xjmJ+/pyNtaomYwc22Ieob/mqoXtizNmHkSoa+RUc=,tag:Y9bYxONIBnJNkfS4E29r/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
