apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    metrics:
      prometheus:
        addEntryPoint: true
        entryPoint: metrics
    ports:
      metrics:
        port: 9101
        exposedPort: 9101
        expose:
          default: true
