services:
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
      - WEBUI_PORTS=6767/tcp 
    volumes:
      - ${CONFIG_BASE_PATH}/bazarr/config:/config
      - ${CONFIG_BASE_PATH}/bazarr/data:/data
      - ${SHOWS_LIBRARY_PATH}:/shows
      - ${MOVIES_LIBRARY_PATH}:/movies
    labels:
      - diun.enable=true
    restart: unless-stopped
    networks:
      - media_net
    depends_on:
      - gluetun
