services:
  dnsmasq:
    image: strm/dnsmasq
    container_name: dnsmasq
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 5380:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    restart: unless-stopped
