services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    networks:
        - media_net
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:61208/api/4/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    pid: "host"
    read_only: true
    privileged: false

    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_BASE_PATH}/glances/glances.conf:/glances/conf/glances.conf
      - /etc/os-release:/etc/os-release:ro

    tmpfs:
      - /tmp

    environment:
      - GLANCES_OPT=-C /glances/conf/glances.conf -w --enable-plugin smart
      - TZ=${TZ}
      - PYTHONPYCACHEPREFIX=/tmp/py_caches
