services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - media_net
    volumes:
      - ${CONFIG_BASE_PATH}/grafana:/var/lib/grafana
    labels:
      - dynacat.name=Grafana
      - dynacat.icon=sh:grafana
      - dynacat.url=https://grafana.phoenyxlab.duckdns.org
      - dynacat.description=Observability
    restart: unless-stopped
