services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr
    networks:
      - media_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_BASE_PATH}/homarr:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=c8ea4f015731a894e73437fa150c316f63939f66a688fd948278f1ba979623ec
    restart: unless-stopped
