services:
  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    volumes:
      - ${CONFIG_BASE_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_BASE_PATH}/homepage-images:/app/public/images
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.phoenyxlab.duckdns.org
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    networks:
      - media_net
    depends_on:
      - gluetun
