services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/jellyfin:/config
      - ${SHOWS_LIBRARY_PATH}:/shows
      - ${MOVIES_LIBRARY_PATH}:/movies
      - ${MUSIC_LIBRARY_PATH}:/music:ro
    restart: unless-stopped
    networks:
      - media_net
    ports:
      - 8096:8096
    depends_on:
      - gluetun
    devices:
      - /dev/dri:/dev/dri
