services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:latest
    container_name: suwayomi
    networks:
      - media_net
    volumes:
      - ${CONFIG_BASE_PATH}/suwayomi:/home/suwayomi/.local/share/Tachidesk
      - ${MANGA_LIBRARY_PATH}:/manga
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    networks:
      - media_net
    volumes:
      - ${CONFIG_BASE_PATH}/kavita:/kavita/config
      - ${MANGA_LIBRARY_PATH}:/manga
    environment:
      - TZ=${TZ}
    restart: unless-stopped
