services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    user: 1000:1000
    networks:
      - media_net
    volumes:
      - ${CONFIG_BASE_PATH}/navidrome:/data
      - ${MUSIC_LIBRARY_PATH}:/music:ro
    labels:
      - diun.enable=true
    restart: unless-stopped
