services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - media_net
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80"
    environment:
      TZ: ${TZ}
      FTLCONF_misc_etc_dnsmasq_d: 'true'
      FTLCONF_webserver_api_password: ${PH_PASS}
    labels:
      - dynacat.name=Pihole
      - dynacat.icon=sh:pi-hole
      - dynacat.url=https://pihole.phoenyxlab.duckdns.org
      - dynacat.description=DNS
    volumes:
      - ${CONFIG_BASE_PATH}/pihole:/etc/pihole
      - ${CONFIG_BASE_PATH}/pihole-dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
