services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/prowlarr:/config
    labels:
      - diun.enable=true
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
