services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/prowlarr:/config
    labels:
      - diun.enable=true
      - dynacat.name=prowlarr
      - dynacat.icon=sh:prowlarr
      - dynacat.url=https://prowlarr.phoenyxlab.duckdns.org
      - dynacat.description=Indexer Proxy
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
