services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_BASE_PATH}/qbittorrent:/config
      - ${DOWNLOADS_PATH}:/downloads
    labels:
      - diun.enable=true
      - dynacat.name=Qbittorrent
      - dynacat.icon=sh:qbittorrent
      - dynacat.url=https://qbittorrent.phoenyxlab.duckdns.org
      - dynacat.description=Torrent Client
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
