apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: media
  labels:
    app: seerr
    app.kubernetes.io/name: seerr
    app.kubernetes.io/instance: seerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
        app.kubernetes.io/name: seerr
        app.kubernetes.io/instance: seerr
    spec:
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:v3.3.0
          ports:
            - containerPort: 5055
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: seerr-config
