apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: infra
  labels:
    app: pihole
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        app.kubernetes.io/name: pihole
        app.kubernetes.io/instance: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:2026.06.0
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: FTLCONF_misc_etc_dnsmasq_d
              value: "true"
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pihole
              mountPath: /etc/pihole
              subPath: etc-pihole
            - name: pihole
              mountPath: /etc/dnsmasq.d
              subPath: etc-dnsmasq.d
      volumes:
        - name: pihole
          persistentVolumeClaim:
            claimName: pihole-config
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: infra
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: infra
spec:
  selector:
    app: pihole
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: infra
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: infra-pihole-admin-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pihole.phoenyxlab.xyz
  rules:
    - host: pihole.phoenyxlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pihole
                port:
                  number: 80
