apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
        app.kubernetes.io/name: freshrss
        app.kubernetes.io/instance: freshrss
    spec:
      containers:
        - name: freshrss
          image: freshrss/freshrss:1.29.1
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: CRON_MIN
              value: "20,50"
            - name: FRESHRSS_INSTALL
              value: |
                --api-enabled
                --base-url https://freshrss.phoenyxlab.xyz
            - name: FRESHRSS_USER
              valueFrom:
                secretKeyRef:
                  name: freshrss-secret
                  key: ADMIN_USERNAME
            - name: FRESHRSS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freshrss-secret
                  key: ADMIN_PASSWORD
            - name: FRESHRSS_EMAIL
              valueFrom:
                secretKeyRef:
                  name: freshrss-secret
                  key: ADMIN_EMAIL
            - name: FRESHRSS_DB_TYPE
              value: pgsql
            - name: FRESHRSS_DB_HOST
              value: freshrss-postgres
            - name: FRESHRSS_DB_BASE
              value: freshrss
            - name: FRESHRSS_DB_USER
              value: freshrss
            - name: FRESHRSS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freshrss-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/www/FreshRSS/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: freshrss-data
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: media
spec:
  selector:
    app: freshrss
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshrss
  namespace: media
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - freshrss.phoenyxlab.xyz
  rules:
    - host: freshrss.phoenyxlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: freshrss
                port:
                  number: 80
