apiVersion: ENC[AES256_GCM,data:PEI=,iv:o4gXGrJYxzS3Ueaku+P6xthmNYCdZuqzu2fpB8zBLuA=,tag:P+nM2y4RUIB637OjU0nE3w==,type:str]
kind: ENC[AES256_GCM,data:wlgneOBA,iv:/vGEq3M3jhHXRRFJbSOAjOt86eJ6OQqpVvARUdA2uyI=,tag:fxC5LHCLxSydl9yO0xiA9A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:37CUs8WyKEGsUnFabSz0bw==,iv:BFC9jo1q6tUE6USDZBT2kMqxxttkh3VWHqgcLVHfqSs=,tag:ZstPREto7oX1OV3IOmgDag==,type:str]
    namespace: ENC[AES256_GCM,data:fFnvT1f+,iv:GUFzLnCEBqjVuVVOEYsJLBSdeByvTZEagiYRFF6eyfM=,tag:XOEsAQ6j3d4dBbHhjWQVHQ==,type:str]
type: ENC[AES256_GCM,data:yacfleDo,iv:ZV2/vdIX6o7x3MkaVvAjtdnly8fhhYffBBX/aeepiu0=,tag:nE7FStCF/FtBqe5At3A7Ww==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TSw+YCYUpUQu2emNflbsIsbz7M0kWtmdOsMkcUUUUWc=,iv:h3dldz4lXJIWkrDYz5ppvGgI70OyoQLuh49UBsg7cRQ=,tag:9EbGwY8B5xWEU1DyVX9c5g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Z4RyrCVlkLiwhYW2BnjHzqNoo1xyBUveELauq7Ch01+uzMTcIGifelbuoqWQGzKiyNsfeRJUowmlbgjfOjgeTA==,iv:dF+22YXVeSJqdwKDipetHopshDORFLiKypXIGsFCpZQ=,tag:8tYQJD5yeSBySqRvhfi6og==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DaR2+Oz2ctbAVV9/1Q0+v76yICPaBr6iOQykBEjV+sqOA0FPEib98D/vawo=,iv:MbMODyKOuT8tqz5MNRla5nBblJaAhwhd3IGdvdNzmUA=,tag:iC35VOmR6NfJD7Rvp91V+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSm0vRWF1TmlScDZIRE4r
            VW1YbmNQNEtKcUpBQlRDaWlYNTE5SDRncTJnCmpxQm0xa2xrNjJJM0d2cGZXZExt
            ZmRJVWpPM25WQjBmcDMwZ0hIa0NJMVkKLS0tIGt4UGZiYTk5L1NkaXRkRHhLbXdI
            RmM5eDlIREdsdXJEWHhBLzJ4NC9pNUEKyo8wOhvukOuVQeOm0M2COwzJIM8dP8jt
            Xu0RtBeZtEMVya9Ww4du5B/ZL7XvFoYaeD2ZUF7QZsYRK2XqIyZB5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-06T16:10:38Z"
    mac: ENC[AES256_GCM,data:pluB9jGDWu3AiCJ9unhgueJFrRCdB/6PcEDB0sSciPXS3kDXtkuWwckhblK81btYACyaz5dEnZFbQ9scbl5gdBai7TjVopT82RFGoi5oB1YljmBh43G7oPiLVsVtCpdtsQyyycDUPXlAc4EiRsaZP6fyKkY/vWkgNjOG9x72sPM=,iv:N2eG0GnUg6WhO2AFf2ro8xE4YkvtLrTf64cgU72WJjY=,tag:/CLDnbCYoIkTlNiAHJw/HQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
