apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: media
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - bazarr.phoenyxlab.xyz
  rules:
    - host: bazarr.phoenyxlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bazarr
                port:
                  number: 6767