apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
  namespace: monitoring
  labels:
    app: speedtest-tracker
    app.kubernetes.io/name: speedtest-tracker
    app.kubernetes.io/instance: speedtest-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: speedtest-tracker
        app.kubernetes.io/instance: speedtest-tracker
    spec:
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:1.14.5
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: APP_URL
              value: "https://speedtest.phoenyxlab.xyz"
            - name: APP_TIMEZONE
              value: "Asia/Kolkata"
            - name: DB_CONNECTION
              value: "sqlite"
            - name: SPEEDTEST_SCHEDULE
              value: "0 &/2 * * *"
          envFrom:
            - secretRef:
                name: speedtest-tracker
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: speedtest-tracker
