apiVersion: ENC[AES256_GCM,data:sLE=,iv:p6+hJGTlm9eQeegb6u5FzllPvPp1XlTPohM7QoX+GYs=,tag:Clb0FS8rnzj5muyThN+mJw==,type:str]
kind: ENC[AES256_GCM,data:iNqWtazM,iv:8bd5iCgkgR8V/ktwn3uOk/fn5HX4ntwG5Ya/vioAbxM=,tag:THbsxTGzbLfhbWs3MQ7j9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:L2TSidxM9fzrSe8G79vGwsc=,iv:tImNdowApmY9Ve6odiIAWHctwskqn22nyJxcN8nfbjY=,tag:b1U+tHl8QwSA2wW7GukvUQ==,type:str]
    namespace: ENC[AES256_GCM,data:nz36YnDvhhd6Kg==,iv:9tGTOeEPlYsgmYI3UtiaqHZdH8rPkGBL4fYSnjXJBLg=,tag:B7DgGA4eOJl66LKEOuvb8Q==,type:str]
type: ENC[AES256_GCM,data:E1+2iCtl,iv:/z9Ibv1zbaqKgB0E1AcNYC8udWDBbfrAkMplirQeslQ=,tag:qzTXBpzXuTb4LL2X1QxfHQ==,type:str]
stringData:
    APP_KEY: ENC[AES256_GCM,data:O4v04GaUNkLaYXCTDODThVZVtk30SHER9yRYS/q5SAqDddu9hMEEUlpdv4MBCtHlBoep,iv:7YZS2WhHIyx2FAZoAkgJDldruiLaMskEAhb2gDwQ3Z4=,tag:LPUWKK6vxO7+RxDDptE1IA==,type:str]
    ADMIN_NAME: ENC[AES256_GCM,data:vG3+bA==,iv:dWHy3gZqHusNpmYcnRsvRFUEojk59MEVIeX2W9xZoVo=,tag:KxS4Q+qyRLm7O9TpbTU0aQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:HHABA5OuFKKpciykdILq0ux86+2oQBaz1w==,iv:0Co2RzcpEaDkaaD7NRpkCexc7/vCPWDuz2MFFQ1Dxho=,tag:bdTtctOZLL51auGYoG5TdA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:tSmVIc73LSTUFrk=,iv:fYgnNnWpuU3NybmsKSWqy2+saI2+RBwxUTNBoQFL3R4=,tag:ukWkibf/xmvDS2PGtCy8Bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYUR2UlFMZm44RmtEVElF
            c0RlbytMUFJlV0d5WHhpWmJFNDlNMzJLVXhzCkR6VlFFVy9QREJSL000dVhWVHpL
            cFZ3V2hvN2h2NjlWZHhmVEQrMEtZNTgKLS0tIHUvUWFTZklpcEd4QlBMcDQ3WUVX
            Q2xkZm8rRmtzVzBTU05JRENvQ0gyMzgK0iDxrJ6VSU454TVxIazysUj48shAJjmu
            9z5EbOpCp1UtH41lk9CgobSs+3CU1QXosXf49QUJogQg7GgyILObvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-07-01T11:03:39Z"
    mac: ENC[AES256_GCM,data:kkGq+1J8yU3wN9kiceZQxXksHHVyd9uFlLaL60Pox7Uluei+XrVkcazgjjwcOdE3sdT6G6CFFA5w4qhUq4U3ohRivZMX5+XMNQrM3RhPUlBKrrbBfCy6kBo3af57cZUKUiuiNrQT8/f0oBisB4SqLmpIznit71A1qgeHDdYfiOw=,iv:5C5BEi/YSvaVPcLSDMzQYCCLhmGZMkTxl/tUirkSPXY=,tag:Xs/MkAdeaqAuZK6+fAsHTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
