apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: infra
  labels:
    app: pihole
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: pihole
    app.kubernetes.io/part-of: phoenyxlab
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app: pihole
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
