apiVersion: ENC[AES256_GCM,data:t2M=,iv:RlhmuPRfkrzwFzNAa4IIc/b4PrdLRPZbevFBcBQ8DO4=,tag:3jZHr/YR2Y3IoMzgxA4hiQ==,type:str]
kind: ENC[AES256_GCM,data:k7KdhmZI,iv:ylYISPDAE452haYiK5kcK1gtk8D130mFwXK5tyTU5gM=,tag:JSfbZcJmxGIWnDZGW9u/KA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6KfttZ284oqL6w1TIg==,iv:XDTa7E+DfZdJykux2gfpxuXuBHBz9AJysUYAmH30Yyo=,tag:XIa1mH97BUA0UZ/DZC2QmQ==,type:str]
    namespace: ENC[AES256_GCM,data:mDBchmw=,iv:nHw3RDMdy9wSQBaN1/q9eS4/4SfQv+66O72Q/f1nIgo=,tag:lc3ZxOO21HqmAq4gKwbWRA==,type:str]
type: ENC[AES256_GCM,data:ZueR1CCx,iv:6I1fi1lAB6e7QYKEv9fnz8OtyyaDvRy3Q8R/5eyUsN8=,tag:JfSSqJgoo+mVdD6Cl08t1Q==,type:str]
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:1nFqlGVYYxVj2Mbnx18EAcsWl91JsphaRdhZywzSlKg=,iv:Q/WyGQcVzc/50fCF5EdsbBTAfkb80myguk172Pevwcg=,tag:l02KmrOxuik/hIHNISBOkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcFdxOEN3OTBpYXU2ZEZG
            OG1GQUtUd3E3WFFzeXNOdzV3eHFIWkMwUWlJCk1WWWFEUjdTdnRHK1djRFZ4c29x
            TU9zQWNCT1psSmMrWkNUUEViZ2ZIRmsKLS0tIG9LSnBYV1NzUEx1VWg5TjJ3bkU5
            bUR0MitLTGEra0pBclZmY3pERDZEZVEKEkDVG2WxSRV3PGGlu9DPkem5Wju/92uF
            lKI+yBQXHJqmOrWTK7bATCLaQ1jsDMI518cIt+p6Z4zwKixdcMq25A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-07-02T11:54:51Z"
    mac: ENC[AES256_GCM,data:yRdJS/L6djzWHKS7x+FJ4OaQxKpC76rFRlOsvJSPbMK9qqSPhVf0HgDverBNAFL7sdO+SJpxj+oyRdnIAAP0dNw9+G02e4dNUaQZZFawtEJaARW565eno9vVgW7t4JMqNRV5UNwq9AQ/b3rns9XfN7M554m/hGm1zsqEovAeeeU=,iv:iz+4NgnII7opN+x/qG+WsTxgKJih1LYXfDdZhDDFJ1U=,tag:Cwq07oh4hT+B52klOkEbsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
