apiVersion: ENC[AES256_GCM,data:r18=,iv:wWKFIkPm8g818tx258ujh1if2gFr+eroO+gwxyee4NQ=,tag:Qz7+z6TO3+0Zdyjkjlfj1Q==,type:str]
kind: ENC[AES256_GCM,data:ZYyJ+W5H,iv:e2vCPj91EQmalEFa27FjRRHv9h44fv2ABlrIJuAofwY=,tag:wbsut/w5LWa1rFLIw2sb9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x/mDe3wlw3rrAzX82SCM,iv:ldaeKSm2vvRfsd046PZHMexkRzQT5tpOynTpO1gSpWg=,tag:NNyhx0POjv2lz1jemmxxtg==,type:str]
    namespace: ENC[AES256_GCM,data:QT0tLv4nDxCsfJMZ,iv:RSGhzdq1V5c12/hIqGXD8K+4cXhczaD9oWDzwF0kqO4=,tag:zli9ZHXNwV9XeeUuFIQdjw==,type:str]
type: ENC[AES256_GCM,data:BT12y719,iv:5VkWF66ffqy9ER1ZNvDnW0owH918+7/wPmw+P6qqJPI=,tag:OnHgIdYty2loOTgY4jSBbw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:2EyDDou8XE4leRf/2hBEf/WvVQOzq7n1wbdFCSWTfHO7fhWrJYRKk5hBNed5FAGJoKhLc5xPj6n+rA==,iv:1SuYzqNHHLrwC3nJfr3R0dt1wvTjxV7bQOHQKzigZB4=,tag:u8bsLSpl1SyD045LKPqcPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaUNyQkhvYmhpUzBxZ2Z2
            TC81ZU94bzJRQXp5QWFlU1ZLRkQrT1czaW5FCjBSOXZXSmkrZVFSMTVkNGN3aU5G
            ZE11cy96TDVBVzVxbGtZTmNIdHRNOGsKLS0tIHFMR2pzRVhSeXkrRENnVnpoV3lk
            WXkxcGlnbWxEQkwwanRiVGNkQjhpeFEKSRiFbIo/SRea/ihdvnryZiAp6cpTjUCh
            6dtcxxmA0IpDkE4K1zdkQujnOUQty9Op1QNHb8r4djt0Y88Mzf+PAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-05T16:20:29Z"
    mac: ENC[AES256_GCM,data:tS5xlw9bIarWVtGXlE+FtGqE4Av+DHuRzI60zJ3mZEQGd79hdHDIYjUyHIsbgKOOhG5afFqQTW+qQElaB0jaWCiEC6Azu5q0oJ2yK/R/nuoqZngdCZjEBu9QZyQZagqq5bI6F0BjFl7lv7nMRr0/Ppq1HC2Us5RkBq4IhHyDB3I=,iv:OyyLAS1Eo+LVkP4de56cEBG3QkA7HotWWeSgzeY1ePE=,tag:DjvxolW0uDq6f+6nzKyliw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
