apiVersion: ENC[AES256_GCM,data:smE=,iv:5gvtu3aAEGv1uOVP6y29HQwwegaFv8WGHS8It0/XMic=,tag:JHe+7/WjIVhMBLYbYArXAg==,type:str]
kind: ENC[AES256_GCM,data:oWTL6yR5,iv:38SFbAuxirLu7UpatKgZV9c3oc3fJICZck5QTlAijl4=,tag:PEBWl9xm/O07eKe7AbIpWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sM6BnWvsEXxCWfKhQQ==,iv:Q8AEFsZUNS4Gvf69rwbdX4UHWRi5Rsxk5h8Sa50B5Ts=,tag:0D7g4WM5dZSmUaPyRKpkVQ==,type:str]
    namespace: ENC[AES256_GCM,data:b21/k3k=,iv:1pnKXlwT/J2V40xNH6vNKHA/lv/z0FEQT4vnc3FQi/E=,tag:shvHNdMjCpTWFqrAM+h5dw==,type:str]
type: ENC[AES256_GCM,data:kDX0sejY,iv:5hHcKCquBwa4U3KPZM10QG9kMsL12aYq2JshsxazAjU=,tag:kDAk5hJ6szEuMy9mkBbk1w==,type:str]
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:UYy26f2p9lD/V+u1srcUUtVFO1k8qQBB27fbmF77dNOwc9A2ZfG7nevmIwvIt8IbtABhsdiOQTbhmBd9goZI1g==,iv:UV8+QrbP6WL3GdhKwby4dUUxJyJY4pFNrKDGjNoaNwM=,tag:5sbG1auSE2BQ+ttRv/kRXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cEhPUjIvTmR3dUhxUnZF
            L2g1a2gvbFo4VncxbGl2N0MxeW5Yb1NkaVdvCnhDcUVSbTZsQ3BEUWxTaGhqa2RR
            NlRpT1A4OTduSkc3ZC9NZ0M3alUvb28KLS0tIGhCeHVWMDZCSm1STmJTblQzVlk0
            VkFRQzY4enp3ZE9QOGF2TDVZSmc5U0kK3+ElkFgSP1R2sixaLwneNEuXCEcOn+vF
            G6LbII5zjthsRjIkFL6x/iM4xyvM05uNlCLAfAiJxumY70/3jGqH5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-02T14:36:31Z"
    mac: ENC[AES256_GCM,data:ws3u2bcrnsojALn69H6IYtcVNaLmM2JRrRJtNkG7w3TnH2PTrkl+520vcrCUcnpDMurhMmOQT5FTp1cSMZVEJ3O1EVANMW8C+d+1/hnyMxch+D56bXKiNbBEDmEo/OWf+LF65npex/oYV53+8/7/2wzYds5eYo2d+ysOaJtNprY=,iv:6rjWOuduYJqpj5HlUA0IQ8xN2THVFBx3D/CyeEfmK0g=,tag:odtrj2wnd3iR848bTWBaJA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
