apiVersion: ENC[AES256_GCM,data:4mo=,iv:jn6P2r1yww9rwcYms3GNH5EDbMI7TQFrBtFSx68VSUM=,tag:xx9fTsM/MrVRdr7svLVGhQ==,type:str]
kind: ENC[AES256_GCM,data:xdIEwjSd,iv:nAQxDtnmi9qDpIcpA7P2Hd6jIGJjyDXqCqnPbsCK7Os=,tag:FqdKyBaeJgGBUytrKz0CGQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WooC1iySQjpqpdCusQ==,iv:ae8sP3YXDTvx6nNHbFKOaE0eJKCV/GFQZl9EcmyAWAw=,tag:DAooVIC1X+Qg+7rRasAzRg==,type:str]
    namespace: ENC[AES256_GCM,data:x2oggtg=,iv:pkeDaE9jvFXylLGwsBIBdnrYDaOxA90q+mlCcyADI+U=,tag:+s0zoOggsPhm8vuF1n26IQ==,type:str]
type: ENC[AES256_GCM,data:1BBRMrxH,iv:2iMlDrjtUFQ8bwaz2OBV+3q4Y4Odpi3dxkLSs7q6dzY=,tag:na37SiPyfkUO6ZkzG1vuuw==,type:str]
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:wyyFOuru1M91fb9LjKUq1FHFYoD6m7AuD8vtIo0VkzE=,iv:+l2dw0nwwkplA4CtjTehw8JVQRLR5xtfDKDIHVgzfQY=,tag:1BZMvADJ4R22C4LAXONR8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN3ZlV2RsaGo3M0YvZkFw
            OUdTZjhNSjVXQk9yckN6d2JiWlpqYUZWVGtzCmkyREtSZlhOVmZVMGs1RGlRMytE
            UU1Ua21MdDY3cTlJQkM5dEpCV250aXcKLS0tIFFKY2x4UHZkZ25talczclROR25y
            d0NWOUw2Zkswa1JwZ01TVXdLWm9aNlEK/b9sqhfFfhyghO45kM2nYHEVz2l+VmJz
            9PXyFbgWkWAZR5ckDzgXDwb7vIWzssZWO6xctyOdYkRiPen6GIfm6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-07-02T14:09:28Z"
    mac: ENC[AES256_GCM,data:zWrlcxSIHjVPnwdcSSvnadLuEi0I3hwubtrREIrQtlQ22yiKfA4pb/+kY6ePpszFp2dXKcG1QhxWdDf/SL9XxPcotJ2+FeTxhMBwWM+O3knY11WR3VTRhJnGV6E7uqFXWKkMUhtDmgwKWxKKsg6FDmpAH1VYfjBzJD9JukBVjd4=,iv:9rQtBh2OYZE4CIAKD+zd+LpVk6PIGKQoe+URLrB+K3I=,tag:sIcDmxRjDSZVUaqAi4oJ9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
