apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: downloads
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
