apiVersion: ENC[AES256_GCM,data:Rdw=,iv:5NUvhdjH1BxV5Qhv8883EYi2b9WCAhhBlkSs0LJy4gQ=,tag:5HQ3FBcTXImUss+59pF4xA==,type:str]
kind: ENC[AES256_GCM,data:Y31iRYCj,iv:AvM0VuPzJTDQ6VeI+JLzR4LpxuMZqgzShgQbvo9XbrE=,tag:cXVfWx23nOX/fA2Ds2W28Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5zIqQN4ESGhO6TMFQMRh0XrKPQ==,iv:KqFa0rx1PfP+/9BEWbRLzlQzNBInYGEZPHqAIOxpHzw=,tag:8dptsHMbw6lXpDERIUcxwQ==,type:str]
    namespace: ENC[AES256_GCM,data:RVe6nFOJaQ+AAg==,iv:2uDywQMSBb1Wk/we81XUA9uN//0sl4zvOsCOoN5tOGs=,tag:NG7yjaUCbtNfkCPqCHJx5Q==,type:str]
type: ENC[AES256_GCM,data:1I6os8/A,iv:J4WIiQvvP32k69MRzrjdq9tQ3ln3smemT9DI5P8Y/ec=,tag:lxglZbfBBtGzMmr7yrtheA==,type:str]
stringData:
    webhook_url: ENC[AES256_GCM,data:UUBAIGV4Th0LUlBJbwr2YAF7JPbGMR7O3LqYdLPyZ/vWIn2LHwaw1OF0nf/7xuvTxAfV0ZMioGjUCE6D/FHshw6+tAzCSCAeR8CXywJXXdWFrmvq+l8MwAvBzmvwXOQhetS/vyj6S3NuvPt5ek1Ji2AP/4GUvvwtbQ==,iv:FU/DkuKWG5DrQ25mjhHw5H5dlJxITWNOdrwK+BoLiA4=,tag:XZgS9cBunZr+EcNPpR70XQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVDUyOGpUMEJmcFFkUzY2
            bFlvb3JFZVUrQ2tab1NGb01OMDNlMEhqclJJCnNYR1puTHBUMGYvUXI1d0ovd211
            aWozK2pVRFVsWnBQc1Nna2hyY2NNdzQKLS0tIGlPRU03TlpCcmFadlhodGFBSzB2
            ZnprWFFSM0ZzRGpDRyt3ZFZnR256aTQKHuUdI4hUvRZcYz1+WNIeUqejAlsh3wv1
            +kozhsoWZRaiSlswEid+N9TQV9fG7drsQf6HHG3ryq1VlYLSbel6Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-03T13:18:32Z"
    mac: ENC[AES256_GCM,data:G5VeawWLMJlcBCDjLbfJDGNrwD+aibwHKkHr2UFp3D3ze96ac/0NZM/yxr2waPlkjm4T8RS0EwJZu4VE2YzAtiDpO4SEtV1xpNsNmlc1KfXnNLbpBERKVHl2yqVPGVOygfpn6u2syxlRCZHwD9/C0OJLRi7hdhrOAzOFVkAt2Y8=,iv:6LIzdRP5ZxEU/Awbg5cxKgtKZ565GtWGVj+hkdpXe1Q=,tag:BCfQ0KiFhV8UUGKWL/fV8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
