apiVersion: ENC[AES256_GCM,data:Vrg=,iv:/Tm8i0mKiA7EScUXvKwK3USvKUfNYkXk5lEW0qauMR0=,tag:9vl7MXkDzKjQgiN2S2Fulw==,type:str]
kind: ENC[AES256_GCM,data:o4BMrUsd,iv:J47MWKq1OMu9IAUTE/lkIHzt8UAHrMpkCuI49ey8LSI=,tag:7iSOHKv2QkJ7fsR5WUiKoA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JatWHD1ULv5kz4er8A1Y,iv:3I15ZYTkZ1ab131hsLet6tF2OGAZDeDikbyvI3Muzrk=,tag:Dp43DLa0jDUj//j+YG4pbg==,type:str]
    namespace: ENC[AES256_GCM,data:TpTXMjs=,iv:VzdWU0plAcQGpVHPL5Gbt7pVc9oUtNqX7Dz5XK6Irrk=,tag:GHvzauFogXhFYEC7p7NJhg==,type:str]
type: ENC[AES256_GCM,data:fBXao3g6,iv:1cHUGL5pe6xgBh15aoq8MG/TSUsprgb9UgfcKiKR6Do=,tag:SSSZLbDUaGB3ZQJCRkK2vg==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EpD2keDUuekf+pz9/xfQz1oL4MGBUrxbtpD672eKcTzUIAhYh5ksTsSj7Yo=,iv:0YqGSQw3V6HlT0hYTlrpt1vq1dogFIMuECQPKvEjilU=,tag:4WmE2TiwxmZ874vo9avCmg==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:s+oDGg==,iv:eObED+/YS9wSiJ532x7PRTDeZaT4UwUxOTC/fKZwEvU=,tag:zRRHZFmoPnBZe3WpkJVFxA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:ow6/0gYoVEQ=,iv:o/JbMdvFwfMAcN5/nOUSf5ZC7prcgEPLWz77YnAIj5Y=,tag:nNElAVuq+GAc1+LwcraavQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:WcmzZXp9XDOnTPRsGmCJGo0w1Q9QFwKYFA==,iv:cBqQfmhTKtJwyO+0gKz9jha/zJXEh2fWl4IH/L/lKAw=,tag:o7EYhwNp2RXmSlPVkWGKeA==,type:str]
    API_PASSWORD: ENC[AES256_GCM,data:SV4+X0zft0Mf1/I=,iv:zPkmCxpGHEpgKgmejVTPuGnHe4bJDUotTSnEfg2c5Fw=,tag:lIvANVAe21TE1khELvenlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydE5xZmhSWUlzaEFaZnp0
            dkdoR21zUTBkbjE3MDQwbVpTd1RFSEY2S0VBCndzR1A4MEVsQ0YzeVJ2U2ZpZ25r
            VkFkU2h6d1kxbjczTFFTMC9JSTlhRmMKLS0tIDFqcnh5bEpleUZERzVKQ1JoT290
            RkNGRFFOYzdtZ0w5Ykk4YWJSazZFYncKE3Ii9of1XKZDeTuTAQwA3123tdIf8S+H
            TVF2YIogCoh2q+dcLJir6lxG1xNC1YO5Mz3GkfMT2HHl64QtelcXWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-22T16:06:19Z"
    mac: ENC[AES256_GCM,data:ROFzAKQoNwGUtS775MGIiMUYdLEhfGHqgCFXzP1ESTv5iNEe8y5J2ZOqmMoa6eXpi+3jtQeFtVHnFlWrj/KOkYmiL/hVbr6G9jAukdVm9L0RgJhBQjM1iFCe578N7+7oGTRRoJX2roHWgrF3A8yVxBNYBMvnxz3YI/C5BDsLcqc=,iv:q2EKJLz1lHR1jyoYNZDls2g0ky/LimYXd+BU6gVPz18=,tag:LDcisrlIRfeSE/g/XRfeuw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
