apiVersion: ENC[AES256_GCM,data:/dE=,iv:ocC3SxK+MWrIJIqm+ClxUSQoW2UHtTVLJM4PoxutRfo=,tag:uBeX38/JGF4BKVutA7FmQQ==,type:str]
kind: ENC[AES256_GCM,data:pu0qVWgT,iv:rBH1Vwl5HjG1VKaiskjUdJdZRwZjqvKA6SfNRtBkRts=,tag:Zeu07X69bSnjfnZBmVQC0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l8Pc0S1sXzX4WcEs/oq3,iv:LGViWBKithf7kjiq+6m/dpyfVXcQs6JNzHvzg/nX93w=,tag:59zrkJK5Dt1aHejpoogEug==,type:str]
    namespace: ENC[AES256_GCM,data:3nSsIU4=,iv:3ZU5h6PyBXFri4TZ0u8rpmHSkk/BmccO1jcN0wmmjeI=,tag:PJMWTtSSKf253Q3/QF2NHA==,type:str]
type: ENC[AES256_GCM,data:VrvysD8G,iv:UkinPWg2eicBJBei9s87zqdoJAVqjGroHTb8H2uHyHw=,tag:NTafnI9qcgRuvGXd4gxUow==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:wREBA3ThwFCjPztI2ZAWRs88Unx7b54RcqENDEl3j6HGo19ToC1zOGLUHE4=,iv:bdJOBHw41u8ZJi+sL+ScweOitrBN3ugjEbUzrvFGQi4=,tag:/uAoWVXotWxvQOTB6MZKCg==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:o72MmQ==,iv:tuhxBhIFhEGxziwZPKfWRX23oSY5Jv0L8IJK8Jje3gU=,tag:v4CXL+qQU8xm5RqMlEyYlQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:G6n4xD6+K90=,iv:gEU4zBs0oxN1T4JKU3JdL08A9rbgpCCN/Pv97Ue2nrI=,tag:JPINnTEgJWxeIGPEN6gLfQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:QA+/08Zs0cxibwt0/3JCjfnLOkbpIwRfNw==,iv:gFCKV28KdMdoF3rCe4/xT/6khljMn0UDfxxGRkNunEk=,tag:KvzV9EtiXtaczBCOMvgxpw==,type:str]
    API_PASSWORD: ENC[AES256_GCM,data:fnNL0PVSzvofPpo=,iv:buAIr18QZDAeWdIdYzV0yBK6g/I9lrQRsJ4dXRyY5Fk=,tag:Lq93cxXpJ4uUH9EQx1EZNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MWIrdGxyNlBaUGdSbE9W
            cHZEcmFzRnRnK2Mxa1MxNWtXMWhDMjdJa3dvCnROSlNjakF3TDJWZFRmUFZ3cTZ3
            QXFwaGxJUk9HN1d4M3VZa3YwRjF2U0UKLS0tIGlxOHdLZkpRMklyUEpaWjZUNzVL
            Znk2WVloeFlscWN0VDFaRUJjVUVoREEKjYIbHkCGrHD9bWstV1sw85IM7WtMrHzN
            /fIamxoLbPA4aRvsGgmqKa51k9OPy8CkyqU/5PqrBAEJlCTWMj8o0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-22T16:02:33Z"
    mac: ENC[AES256_GCM,data:8+es9f0PN6pVsieTylBb4igOFjp4ml/c3017EhvEDKVeYrJoL57QYqGm42F6lzPPgPHqxo7mQX+smsQhP1AwgTw9udD6+k54e2k+kvGY9dsqoRkv8hwddn/5T86o5S4ba6p/givoZmXEo9eQeakok7/osW2nLbQHEGd/Ffo7RdM=,iv:suCxhkSgn9f0Tc1p1EHw4aK0IWf1vngQTl8GCy/G1KU=,tag:/2lIoMD8x9QWddyWzrWJNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
