apiVersion: ENC[AES256_GCM,data:QK4=,iv:MXm7kk4Z53ld4/Tn1AEu3n/ZFhemuAxdTALXpNHvhtg=,tag:56YEo83MTi+2+5GEUVWUOg==,type:str]
kind: ENC[AES256_GCM,data:OGeWrpf6,iv:1vT3jsAIE4YvcICOuwbevrbrwO1G/nqaxRpdhXuVn8s=,tag:Sdj2AWCiHrg7YTUmz0L60Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ivq4vjg4zKmseDrkMU4j,iv:LqdH/X+25IXlRqoqvEoHNdlfSVGUTF1oh+ch7sN8HgA=,tag:iGwPatb0X4VHHN6l6/653A==,type:str]
    namespace: ENC[AES256_GCM,data:xpaKEvs=,iv:NvntCoy+DriWLDQ+tcIjANTweLxETpmA/TKE4nX0eU0=,tag:R3JqkimAQcnVSKnwf+O7HQ==,type:str]
type: ENC[AES256_GCM,data:TeM1fanP,iv:QBkH0I33Z7hPGJgOWkOLlp9/wr8wQuYFEqR6YyIERs4=,tag:9g5zEsabYdRwgUU+X3Xg8g==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YTN2kGiuBFtCm4lyx6yE6itjjoygO7CRA6qA7CHnc01wUAD0LGH8wfj3hrw=,iv:Y4cpO5pLEjZQeRJd3P1RH7N29Zrm+souB7BSBmIpUo8=,tag:0Ddj75KmkFON7WeNkifdlw==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:gOQjLQ==,iv:J1QjIzpQT0woiCIL0jwa6d/duQ7jbaySLoftPhOlpFE=,tag:Q9lQlBS+dIKLD48GZRTfHg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:tCpXOMZoR0c=,iv:+sU94MuAPr69YI+Hm5KzZW0KgcGgAKlXzIXRFlHbOUE=,tag:DW3fYVcMvIE8/gzDX10cDg==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:hDp0dUMj09Eagsj+6Y7cmkbXfszEWpxJyw==,iv:Z0Iz6dyWJ6F6OLlNi+fpWrewZ4d6jYh5OKL3QTdLbxE=,tag:CuyyrDJTVPoiQEbZ8A8vtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N2VncEtnemduWm56UEhC
            YXQ2VUo5cjErTXQ0bTJOM0ZXUlR6NGZjZmxNCndQNk5UaE9saVpaTGhkR2FabXZa
            Z01iVlRManBNWldDdXdiL2srUTlLYmsKLS0tIEJIRmFLY21jb3NJVzAvTk9iZG1Q
            d3MvWkdNeG5jRmpDNkVoNlRWbGhaV00KMnXdgMzMyTyp/10j5cJU4bEtlf5fnjHD
            OtVJdUw6ZRiAASfoPZh+p7TT71cz4X1/QI8mOnzi6Owq60fDcHiKew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-22T15:23:31Z"
    mac: ENC[AES256_GCM,data:aAnIrjFl6+U3aOMdLm1cPI/wGK+lzn6vK0czRUTXW4m4OF1jqAKyOL7juhfHvXipdUy18ZaksjmQvRoKaz5twbdXxcF77XOdPim6GZZ/YX3ycPEh5oTg5FNxMpYttrkxwV0uaWi4tP6MRYC2QxpKw6p8vHB1pMvrp5K/I75Gsbk=,iv:l49DzCnBr7BTC+A370qxLuBLALULryTqIJkGlMFdr/I=,tag:F1uvzN4dwuoAsVqGUhYrYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
