apiVersion: ENC[AES256_GCM,data:JDk=,iv:r+97zwvFEncwJb2foEv+Qaw4vDk9Saqned2t49xlI3Q=,tag:n8g1M+/jjueCL2nHu4RQIw==,type:str]
kind: ENC[AES256_GCM,data:uf1Y9Ca8,iv:dARlFDV6MB3psE1idWtM7YTPlqrfRnpOmJ2kYPnab5c=,tag:QyorMck/0P0/n142glOsQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3yIZ0VzAfcFS4eYdqHA=,iv:fIdE/tRltfvModvrkzDw8nLXV5a46BsHNqCItgw83qo=,tag:WtsF++ghcPxttiJcScmW6Q==,type:str]
    namespace: ENC[AES256_GCM,data:EZJ1t8SMliVz,iv:f8EAmFSuGZHa3DCGUVoPm8kxqscMRAU9h7ZFkw4HJSM=,tag:fGTeKCV4hGCDY8RnlAMONA==,type:str]
type: ENC[AES256_GCM,data:h4wdmkcw,iv:c+lNiJG9kWzwkppZETlCGRNnD56pl0E7ZHs9sepbxoE=,tag:3GXxQbykqzU8ihfD88fasA==,type:str]
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:T9shlAxkdjtk3ZJ7qIPvreR70M8AzuYQC341YGrPTWZ9MGRBNsUf+PmuK0s=,iv:qat7SsIRFWTw39B7bhZ4easfqhH38pFSvCaEkRBWOlw=,tag:+hNkoAU/hafYyuzYQU6nPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SFpkNUw2TVU1bDUwYlNN
            cTVTRlNURjFRVnJVZE9VZEc2NkRFNEthWW5nCjE0RVRrYjZKU2NsNWR0SmRYL0JJ
            UFhZemFtUmJmNVZCdDIxQ20zalJsbFUKLS0tIE9NakttazVGTE1qU1B5OHlRRmZR
            Y3o4VzBjc2ZDeW5uQUNvdEI2UWltK1kKRN6QHFASGZoNwKC7a95ejyFLu2RDVdMh
            sLF5e/6HAqPyOIse/XVgEbpd6PWrPtvAwEDRzixdGE8XaWhb39Nt3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-02T14:43:08Z"
    mac: ENC[AES256_GCM,data:S/fe2ZpEYYG73L9pzkoR4Xr+ZXHwsQQS3eRXouBjDzLzH+3FLiW5r80dNSux+tHmp0VnsXsRJEM/JiTQeceNH8X7sbI0AVXiK+gRlpng+6/OmU7SiMYgpsKMQQzoDvwK5Cn/OFPSpS4szI+Ds5jcRV0D8j9+WLJAqbk6So91fMA=,iv:4GwZ7sSQ6w8bGlhv2iOA8GigDHksoBOAMI4Vb+oqUAQ=,tag:g+xEF5qG4i7p+mJF7LjLjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
