apiVersion: ENC[AES256_GCM,data:fdM=,iv:CnvZRgEyuMURQA64wvKb6YRGfqN6aoP/Q59tmJb9V1c=,tag:AAo4DBtgKdp9/3lwipRJ4w==,type:str]
kind: ENC[AES256_GCM,data:3DnOssA5,iv:xztz7LLkNEMf+AVHXR40kFTeO5tQ5nheLeVg5p6PV0w=,tag:fyeCvhLaI9CXmnA6ECO3tw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1IXFFznjnORbt08zvuEOLvLdxKY=,iv:cWgue+B5UJeAJfmNALxpzP3oscuCkFyKlN+162KYCn8=,tag:0z0a6pH5mpnqlhmukZnBvQ==,type:str]
    namespace: ENC[AES256_GCM,data:uaWq2VY=,iv:6yh9dNg7S2D7Ogky2bBXTxGAE3rkUGfuqf3cClQ40+A=,tag:ofoSeh3K+WbpMEl4sS6pvA==,type:str]
type: ENC[AES256_GCM,data:GxYvcZSB,iv:VMfwiiRmBuNPJN2LJWqmq9amORUBuHLQ9x72vXfDzvE=,tag:6CF/AA/TeIjzz5jDKWNvAA==,type:str]
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:OYRUYbomF85prTD6M31vzB3WOSGgWhhIDdDaDa9j4dU=,iv:19yofBeyA8Px6B/F8WBL5Mc5A9YwBim2CCNx4g40AxI=,tag:A6imjoWg63BMJ3zsTaZ3sA==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:ix284+bp,iv:ucp5YMavWIFsRT375+lM4z2W6uPFUjgQOVtIp8sTCSw=,tag:UdCV6jHnP0GahOXRSFIb9w==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:6yNb7OgGjhJ3scovtGGPHSafAF2zz9gLEc1x9PkNcKk=,iv:8Oa+OEwHz/ojiMdjIwHqnALHweMil+WeYJojWf+eTA0=,tag:nI/StXFh/Q6GD1PtDaRF6g==,type:str]
    HOMEPAGE_VAR_PIHOLE_PASSWD: ENC[AES256_GCM,data:tAGT5wQ0EcCTWm0=,iv:a3QMXYzMZCLqa9XEBTlQBigm5TLtyU1JmUxkFhx2TkM=,tag:YYnl2eqk+oTZhWfk3y3yxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ1hqSmxzaHV2UXUxQ1cz
            VXFUS0VFRzlnR3RLa0RONTFiOXI3WHpDRFJvCm1ja0NyNGJ4U3F4b2YrQTR2M2dT
            bjdLbEdPcWNGZVcwZHM2UmNIQmpnQzQKLS0tIGNLUFhUbmVKWHdMRnlRalY0RUdF
            U1Bwamt0RWJxcGJoUVlKcVpaUE5XM3cKM+3LUlXxKHY0r41347umjWko7JL/8xiW
            oKEwUx3rtMuIXaaeEfAJCo1O/A6ub/V26vcIQyWEqQHBBOqpl+ih8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-16T15:16:53Z"
    mac: ENC[AES256_GCM,data:h/vJUQZuXM5FXuUCOwtGXcCKNPABNrETkf8SBL3qADzw0GIQU01uPQ4XKlSFeoW3vQJy99j24myYGQODzSkJduKfxItqGZcZ43krB5dw/JErWyPVJDaEd98pVMdLxwtwDVXC5k11uQ7cKc2n702EaRpO3BZ6NU//QJlvvFSgTRs=,iv:JIjBFjcbsdw1bisdp8m5jpHY/UwPQe+wvGk3d8gyAec=,tag:OlkW+/cC9TRNAc73yDfScA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
