apiVersion: ENC[AES256_GCM,data:kfI=,iv:b7EyWn3vAe5LlJoBi+0/K0nccHiCfeFZObuzM/+pDvE=,tag:o1rHjq2UH/m8pf/W1xqE8A==,type:str]
kind: ENC[AES256_GCM,data:vh+ruCt1,iv:JQWkjLMHkVSDAq6WMHB4NgstrJ89VlTtqQSwjkOUhVg=,tag:lcmLXD1dFow6TQZ/XKRgdw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ak8SGuAWESlPT+X8rITW2KTP2y0=,iv:PecNd6KzYCPmI0lBLnLSmkD2SyLZZyc/SDwcvVvHZsY=,tag:VWGkpngj5eEOGJe9pNZ4XQ==,type:str]
    namespace: ENC[AES256_GCM,data:qHFa7Dw=,iv:AZfwWF6BcnYQHkf8pJaRdA3Bs4GKGdTbkGihwX4flJ4=,tag:C0SJh2EAOtPc2UGyy7CVHg==,type:str]
type: ENC[AES256_GCM,data:Ai4gcXxM,iv:AUZ/P5AA10SADO49JKkSUMWa4PCgxjxgnZb1fzu/5PU=,tag:ko6p21ioxjtVqOLI4xk2zA==,type:str]
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:Wb47rv3ghbPEWsq5P5fxLr7wgMMrIPmOUSn9n8pBrus=,iv:2eEXsXMFfdWTOxyy5rD96WhRtjZ8XoDZWZplFG4S5XA=,tag:F7f4QBpBuPHuwHqRkS6rew==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:aUmwutn2,iv:WPny1wD9D5BOZJz2He7a9Pc30JgWxHSHmGnlu8D9sWk=,tag:gVjsf72FawDkVAOph7XVQg==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:8bchdac330GxqAlOC3SxfON8odYSDF1Jpk6LtNkgGnA=,iv:kZSjavJb+zNllHhB8sYRl3hHFlh3cADkIqm6t9blkps=,tag:A3ncKqEPvsF3pc7KgvYqhQ==,type:str]
    HOMEPAGE_VAR_PIHOLE_PASSWD: ENC[AES256_GCM,data:GMYfN4Jd1gm4whs=,iv:LkTwLgZOfFMC5UEv1VqZiTqmjqWJsjBAfCIcPNe/g/M=,tag:U2VZThadEUgJfygdqgoe3Q==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWD: ENC[AES256_GCM,data:NJiuhAv4DT6ZUKo=,iv:iqdlb843fDVyRWb23UMUDGEEG7bJEB86vFKkAKStYxQ=,tag:MciECs2XAD0VC2ZRYVZ1Xw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWWR0M0xhTUlyQWpJa3oz
            eVB3dUVoeEhuZnZidkRNbUd1aXRoVHJoVkJNCnc0VnkrNnYyWVBCa3M5NEVoRXZS
            ZmIxZ09panZVZFMyRmNhdkJXYUExd2sKLS0tIEtlaVgwK2ZVTllxVmNob2dIdUFv
            bU1jRENaVjhsbW02SlA1QXRPZ1ZIRTQKdaDqRF9V1NHcuL9q3frzNymx3T2Su6dA
            FQv6K/JVDOgkA1hDbKeQ9tpZGkMkp1W1g0tcpK3WkdNTwJQuKlw01g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-16T15:44:52Z"
    mac: ENC[AES256_GCM,data:VOgPeatmBRyRBtuCs33P+hcTohX4cRATvAMGtovWnaE0Iq0qEjK/4id4JefKYzKof4INHB1KhybpPOjhskXI3s3s0ykfdbH3Oqzmuo470ty/v57TbSuyUGMkQL2M3F7lLnMyPjJpmu5IAOdf45cMNRxv59sRWZgEX/bbJ3kLk0U=,iv:N0aikQ8hSmhfvFDdGeiR7O0zSuKnM2heuoGSV7joKCw=,tag:4jLqDqUFZLnuM7TXecNDBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
