apiVersion: ENC[AES256_GCM,data:iV0=,iv:FxHP7m4UT/MdsjFImuHSU4qLh+umSRMYowoTievq0c4=,tag:NfaaYDgswQ4HAoL8LWPa8Q==,type:str]
kind: ENC[AES256_GCM,data:OnAXMlT1,iv:CFpkIQ6TmHvZ3r6XxgYtLpblXzcArmeaLex9c/rp8Os=,tag:BLHHAsUFPn3y5sKROWBjXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S28usw3fvJ8dfTNughsNb5NncC0=,iv:gRpgvXrp7Ea22OahEE7us/yQYze0hOSRe1vctll6uNg=,tag:PoAEwIAHHFuPpKEDe8DtdA==,type:str]
    namespace: ENC[AES256_GCM,data:B58dwC4=,iv:Gfij9gaEtlLTLzo04wcYjxOrlvBTVkcfq+bvf4bAFZE=,tag:apmUETCMvUa0MAV3u9dj0Q==,type:str]
type: ENC[AES256_GCM,data:iS17aTZR,iv:Fr/Tec8awfHCknuWf1++iItsyq4EJvqBaQJsewx3gpE=,tag:QvboFmvqoBlj3jwJy8D0lA==,type:str]
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:gYbiqBzsa6csZXovBZ+Xbf3CaXFF02p6oYqbVVBzAIg=,iv:8eMnTy02tQAINkExWASnd5nypX9sGLhFJ9EZakvtPi4=,tag:veeJNVgZnBfPAcHw9PO/CA==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:rFI20DuT,iv:kA81jhUVeL9WVMDnSpqrnPqLBqdzcGXIlzweWWr03Rw=,tag:dLo2c/PwHIudVDhi5a+40w==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:cQvgYphg2Vch7i7h/uWBumy0xLegfV4jdIBpwcGyjuo=,iv:WAm6Dv7oAkftWQWFzGi51ldPWU+57eZFz8Gq8fbjIrY=,tag:2R1VF++FxkD0i8HWywzx0A==,type:str]
    HOMEPAGE_VAR_PIHOLE_PASSWD: ENC[AES256_GCM,data:O7YvRFN90OwhELw=,iv:ihx8FHyt6Rds7q+iB20ZvEHRA14hA4GE49SHIdY2GFg=,tag:5brzrHJXf0DgPFoqNWllDw==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWD: ENC[AES256_GCM,data:WeooGN9hBaI3MmA=,iv:GXP5x1feZRIcPjJSsGQ3/NwDrjQlmLFGjXs9c7Bl4ek=,tag:3BEx+VSMnfdoM/CO6xHndw==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:QeIqxEZwHQl3nkapdpo6DXvcxfvRoT4IIjEN6AiL2U0=,iv:azSiSwin39cF8d/O9OnoJW7lW1kjMDwHGL3/iMWL39E=,tag:nr9MIj1PdsTHF8HTfbhWew==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:geRe1v4vwSPfb0MBa/KqDVMR6PbMUkp60bPcuRLpzBg=,iv:Du3SgWIDLgsRX/mBCKlC9WFbGSYM64QUeh0J4TiL0FE=,tag:DXzAaNhNeoGlsEfmjDMkxA==,type:str]
    HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:dBY8hpiBNjtTp7MPwwaInZnUkAALNq9KxYUtBoVusqE=,iv:nWA0Ntz6pXigLqxxyHVnnWYGcq2DNCsjbJO6r+/sKtY=,tag:aEBNLAlMUdpE3D9ZcltMEQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:AI0NIHKw6CIpCfU5HdqzWsVPLF9uTJAkM6nw4b2ashI=,iv:k+hywWNERSbtaL1VvuZaTsnW0Hz52Ho0ZibA+6z4akM=,tag:xbAjOASnzNFyxWRZXf71KQ==,type:str]
    HOMEPAGE_VAR_SEERR_API_KEY: ENC[AES256_GCM,data:/bsQD2vl6OlHBl2zC0J7rA+V1pqihO29sqwibs//V4wL+PiqVMSEzgGSYve/AXaRMQ2atKn/feN8gQrtafqYhp9hCi0=,iv:opZOEaVG4YvBe/hR010y1P+MiHxGFaUeyTZWdqPceTY=,tag:PpRSf3gNrJsRY/vni7datg==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWD: ENC[AES256_GCM,data:OKOL44csElSazxo=,iv:DGulBOe0+8uDHfKnIEFY+lfpwICRiCi4qOQzxMVl0T4=,tag:LuGROllE2XOvF+rSmvburg==,type:str]
    HOMEPAGE_VAR_JACKETT_PASSWD: ENC[AES256_GCM,data:mVJpzE68K8/5s6k=,iv:vCHYkbwPnpqsLMs9U2XKb2+luEDRU5XUe8cS/5xPSco=,tag:kF351FZsNkQHMkqWo9X1ow==,type:str]
    HOMEPAGE_VAR_FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:YLIPXtFl556pG64=,iv:9nPTDg5PlMxDXUiwzzv5ZaqdjMa+AB8JUrlZvuFBDrY=,tag:9pFQL0yyzOY5pJv2yuILLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZi9CSlI3VlBxMUUyK2lo
            ZEEzMXQ3YWNJTGNoenVHTWtPa3FvSkdGR3o4ClFXWVMyTGxZK0NKdjNibWU1Wjkw
            eG93M21pVHpSdm5MaXBZVDRSTjZWLzQKLS0tIEhodUw3bGphM2pFdVpuQ256NFNp
            YlRibDVHYVJhYm81VmNZWVBnUVZqc1UKobx2YgHQYDOrRhs1Mrta8gEjAEZDCmJW
            58G01Ek4kTfG9ReIWqRCvRvVq11aTJ9OjVt9Qx4QTPwFf6+Prna+SA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-22T16:06:14Z"
    mac: ENC[AES256_GCM,data:8DZQREl362jE4+txZrwjVRtFiOQvYLHPcqvWwEnWK28bfuNPI6QASS3RqDkm3yp/YRTXhjFnyDnNMmx+feX2ZcIv1gjLufjDkvwRSHpeohJc7S2Co+AExGGPSbgeWkYQD6KFMGpEyPP4o0tkgBBlKmN1JF5PbEGG14POT7nmNkw=,iv:IwjEzSMxiKPLoyfZNd24P1QjdR4kc9x5j+gWKKcLa5c=,tag:ghG/sRmXq1BFcruKOqVdtQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
