apiVersion: ENC[AES256_GCM,data:QVA=,iv:Ldp0UIye0RKuMajCSsxkegYW4mt3XeabZ0vvv28Bfcw=,tag:oJzK6qYAgzrD2xrsnv9cBg==,type:str]
kind: ENC[AES256_GCM,data:anvEIV2r,iv:H4WVkCGG5WG8tNRyBL4aYVT5vcAf7LHchlDzHPnKTuc=,tag:BHyj8UaqJ2T9nk3yZPM3fw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:16rnQQkO2WZtBZg/EA==,iv:3vcogCB5mKy1XT8B0WroN2aaj3ffb0a5oUGYmQSz+Fo=,tag:dWHiOsrGAn4tn/Il816XcA==,type:str]
    namespace: ENC[AES256_GCM,data:Utlnopw=,iv:pJxr5fbjW3ts/XBC2c7KXBztPRtNlWmgOrUTXZvBAaY=,tag:3JhFAhkFpQrqYASxU+Oc+w==,type:str]
type: ENC[AES256_GCM,data:a6Qb/5Xx,iv:5K4MXEUORBe8DsSWTyf6knixHLJZTZojJESxPgNjQcQ=,tag:AqTqPDP9/sgBDNnlbSLDvg==,type:str]
stringData:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:gy/+hlYYVQk3dyw=,iv:3/QWf9jm8P2924MJ739YzZ4XjNTbBIvUO6SLONeOHyk=,tag:2TSZ8ZE9/l8CTf87VUj4EA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQW9WQ1dMZ3lBcnZDL2tV
            dm0xRmxvdUNQMFJ0OEVWSlZuUDN0dmJ6blZFClNmbThqZEgrSDYvNFJ1K2thYTdp
            WjEzTEticFpqRU5acmlkd1I2c1lXcjQKLS0tIEZMNFBOVGxyTDRQbXNDNGpLT2dz
            L1hTQytIT3dCaXJCSDNvQmk3TTNnUVUKQatjczEWT2Oa+F8EIMtOZoMCpPJ/dZAR
            cMYLjktEzdQyXqkrDthxiFSQabxLSNqbSNWIlpH7IAHg34WwqKlfIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-02T14:43:48Z"
    mac: ENC[AES256_GCM,data:sP+qIyCQPgJIU58EZ56nmQjxm0uKMbU5CAbrNUdghjvhYQTC2TU4W9KeTFoZ3ymKacpFMLI11weW+iK5xCbjLAUHBZjUEPWipnh6u40dsq0NgatCZLWlCQQCQs1r31GY8T2CQaH7WJZuRRNs2tJrCKT1GHcOLqJ33Z2L2yajEQo=,iv:XrtV8gIBxGgciye6AZKyy/3jk1lHwzgF2vNPSxk5d5g=,tag:LwavcnkStvsyB7WE0pMqYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
