apiVersion: ENC[AES256_GCM,data:vJQ=,iv:hQ3tqkzpEpfrsPhlyjjIZ/5/+M32WpH7rxrA58AsUKw=,tag:QETBWxG+Cd50giLACB9TuA==,type:str]
kind: ENC[AES256_GCM,data:OM9DIPyx,iv:2heJR1EMZrI+JsUqLZekwok3yWxz2N/2uIaWkSpEH4E=,tag:NCcR7rF6Fzoy/b6SMfD+jQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ngGsBKrBb2POL1sd7PgOUL/Vz6CKNDie,iv:MwnrLbaD7HBuKn997YjXAFpQHRpQZeLrFxocCCg4pMQ=,tag:tMweecoiIIeUvNPCYmePBw==,type:str]
    namespace: ENC[AES256_GCM,data:23uaTlg=,iv:SlL8RXedW+yG7i/b55XavfhV2/jHyJBIcOXQNLYKd10=,tag:ftcuQBMHbfbGJSa/yPecUw==,type:str]
type: ENC[AES256_GCM,data:KYDdkOtU,iv:jymRBq7qxmsoSkmocjkFnTDO9BQxl0udLiTFHS52hAY=,tag:e0d0T5R+JL5YopPvqqsbGw==,type:str]
spec:
    stringData:
        ADMIN_TOKEN: ENC[AES256_GCM,data:XbzBFWUCp8s4y701tH99f6f9wnqpkMlwA5CKgyP+2eIoBkNw8AILA5RHXgc=,iv:9znNRxcV2KBFTqPVg6my2nAmYnshMTRyrzHPjO2RhbA=,tag:gN++etbvysRAGIvk537i2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTzJuSVBaVzZTMWFDVWd2
            eFpKTHJZa0RHYjBFL2hPOUFmL3BnMUhndWlFCkhHb0VyM2lQTlBTWjN1NDJaajR4
            OXJrZ3pMSFY5UDNSaUlTU21adlF0NE0KLS0tIEdiTEF3L3ZBcit0U3l6YzJCRE1F
            ZjlpKzQ0NWVqNFlRR3o0K09KZDJhK3cKkjLKJNOTUZExeQMqn/cx3uSR3rfTRjiK
            Y88kNKB7z4KebGcYxMw8Y7JypXIou0yyq77J8k7Me1pvxPfhYMql2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8u7ap4warcxem7dr6wtre2xqfx65j0jqdxq9dvwl0lm7kap3f4qp3fqxe
    lastmodified: "2026-06-07T16:57:31Z"
    mac: ENC[AES256_GCM,data:spd48dVteq/3hIdDIdy/3+GYrZTEKPjScO79fTngPD65KrhOLRRSFfzKcxKq/1Me6YSY12xXtTkli9Y7p6XsXaALXY2G15CldraYZkkJdwfSd9RtFIrKxLMWYFN7sVhywbntou6kwGm1tiHb5wUYGNye3rr/Rpvkg2w2PSiG/xQ=,iv:VWTfvUj43jio1hbu8d5ZPk2qfwbAYvq75Rjnb2ZxHok=,tag:5xNKUWdb/7+q687lTnTgSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
